### ISSUE TITLE
Error: Connection url is empty.

### ISSUE THREAD

**Issue by de-mawo** [vercel/storage#102]
I am facing na issue trying to connect to my Vercel Postgres DB using Prisma ORM. 

```
$ yarn prisma migrate deploy
yarn run v1.22.19
$ C:\Users\User\Desktop\dream-factory-hr\node_modules\.bin\prisma migrate deploy
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database

Error: Connection url is empty. See https://www.prisma.io/docs/reference/database-reference/connection-urls
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My schema.prisma file connection string sections look like this:
```
datasource db {
  provider = "postgresql"
  url = env("POSTGRES_PRISMA_URL")
  directUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
  shadowDatabaseUrl = env("POSTGRES_URL_NON_POOLING") // used for migrations
}
```

And my .env file has:
```
POSTGRES_URL="postgres://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
POSTGRES_URL_NON_POOLING="postgres:/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb"
POSTGRES_PRISMA_URL="postgres://xxxxxxxxxxxxxxxxxxxxxxxxxx"
POSTGRES_USER="xxxx"
POSTGRES_HOST="xxxxxxxx"
POSTGRES_PASSWORD="passwordx"
POSTGRES_DATABASE="databasex"
```

The other issue is that, Prisma seems to read from .env file and not .env.development.local or .env.local .

**Comment by Tmcerlean** [comment]
Getting the same error here.

**Comment by janpio** [comment]
Is this still happening for you both? (Prisma here)

You seem to have both `url `and `directUrl` configured in your Prisma schema, and your `.env` file has both the environment variables used there defined as well - so this definitely should work.

Can you use other Prisma functionality besides `prisma migrate deploy`? For example `prisma db pull` or just Prisma Client in the app?

**Comment by vvo** [comment]
Closing for now, please comment back if this is still an issue and ensure this is a vercel storage issue and not a prisma issue. Thanks also @janpio for commenting here!

**Comment by janpio** [comment]
Unrelated note: `shadowDatabaseUrl` should be removed from the Prisma schema as it is not needed any more and can have negative side effects: https://github.com/orgs/vercel/discussions/2515#discussioncomment-6450133
