### ISSUE TITLE
Error when creating new Prisma migration

### ISSUE THREAD

**Issue by kevva** [vercel/storage#114]
When creating new migrations after having created the first one already, Prisma errors because the database schema isn't empty. This is because Prisma needs a separate database to be used as a shadow database. While it's not a bug per se, it's still a limitation in Vercel since you can only connect one Postgres storage per project environment. To work around this you'd have to create another Postgres storage and manually set a new environment variable to be used as `shadowDatabaseUrl`.

```
Error: P3005

The database schema is not empty. Read more about how to baseline an existing production database: https://pris.ly/d/migrate-baseline
```

Steps to reproduce:

1. Setup a schema like in [your example](https://github.com/vercel/examples/blob/de90db0fb90e873dc5b94c3747b04ce1d934cbab/storage/postgres-prisma/prisma/schema.prisma)
2. Run `prisma migrate dev` on a fresh Vercel Postgres storage
3. Add some field to the [`users` model](https://github.com/vercel/examples/blob/de90db0fb90e873dc5b94c3747b04ce1d934cbab/storage/postgres-prisma/prisma/schema.prisma#L16-L22)
4. Run `prisma migrate dev` again

**Comment by josias-r** [comment]
https://github.com/prisma/prisma/discussions/19243#discussioncomment-5907743

**Comment by Radicitus** [comment]
Also having this issue, hoping it gets resolved soon as I'd like to move my db back to vercel!

**Comment by ehwarren** [comment]
+1. This makes prisma + vercel storage unusable.

As you mentioned, neon docs specifically state you need to create a separate database for migrations.
https://neon.tech/docs/guides/prisma-migrate

The vercel docs should at the very least reflect this.  It looks like you can in fact create new storage and link to the same project, then manually configure prisma to use the secondary storage for shadow.

**Comment by RatulMaharaj** [comment]
+1 I had the same issue as well. 

Pointing the prisma `shadowDatabaseUrl` at my own local pg database seemed to resolve it.

**Comment by luisjuniorj** [comment]
Change:

"vercel-build": "prisma generate && prisma migrate deploy && next build"

to:

"vercel-build": "prisma generate && next build"

And make the migration manually on the dev environment, is an way out of this.

**Comment by Rrhapsod** [comment]
> 

Where is this "vercel-build" ?

**Comment by KATT** [comment]
Commenting `shadowDatabaseUrl = env("POSTGRES_URL_NON_POOLING")` seems to work and doing a test migrations seems to have pushed new changes too

**Comment by dev-luizf** [comment]
I didn't had problems using this setup:

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
 id    Int     @default(autoincrement()) @id
 username  String   @unique
 password  String
 posts Post[]
}

model Post {
  id        Int      @default(autoincrement()) @id
  title     String
  content   String?
  published Boolean? @default(false)
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime? @updatedAt @map("updated_at")
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}
```
First I created the user model, ran the initial migration, then I updated the schema with posts model and ran migrate again. Worked fine, just had a connection error, but I tried run migrate again and it worked.

PS: My DATABASE_URL is the connection string available at "psql" tab under Vercel Postgress storage details page.
PS²: I'm using it on a Nest.js project deployed at Vercel, and for the prisma setup I followed Nest docs creating a prisma service and module.

**Comment by ruheni** [comment]
👋

Neon recently announced that the need to create the shadow database manually was removed: [Improving the developer experience for Prisma users](https://neon.tech/blog/prisma-dx-improvements). I would recommend removing the `shadowDatabaseUrl` property from your schema and retrying running `prisma migrate dev`.

```diff
datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_DATABASE_URL")
-  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}
```

Let us know if it works once you make the update. 🙂

**Comment by Rrhapsod** [comment]
> wave
> 
> Neon recently announced that the need to create the shadow database manually was removed: [Improving the developer experience for Prisma users](https://neon.tech/blog/prisma-dx-improvements). I would recommend removing the `shadowDatabaseUrl` property from your schema and retrying running `prisma migrate dev`.
> 
> ```diff
> datasource db {
>   provider  = "postgresql"
>   url       = env("DATABASE_URL")
>   directUrl = env("DIRECT_DATABASE_URL")
> -  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
> }
> ```
> 
> Let us know if it works once you make the update. slightly_smiling_face

Wow, I removed the shadow database and now my Writen Data on Vercel Postgres have reached limits after some migrations. Are you sure the shadow database isn't important for dev ambient?

**Comment by aed0nis** [comment]
Removing that line did make the code go through for me, however I am concerned about @Rrhapsod's  response. I would like to know the true solution to this problem.

**Comment by janpio** [comment]
We at Prisma are not aware of any problems. What limit is that about? Is this reproducible in any way?

**Comment by adriancooney** [comment]
Thanks for all the input here folks and @janpio for chiming in from Prisma. @ruheni has hit the nail on the head - this issue was solved by Neon and we no longer recommend using the `shadowDatabaseUrl` configuration, it should work by default now. 

@Rrhapsod hitting your Written Data limits on Vercel Postgres is unrelated to this error and not a consequence of removing your `shadowDatabaseUrl`. Users can hit that limit by writing/deleting/changing large amounts of data in their database and migrations will count towards this limit. 

Since there is no more work related to solving this issue remaining, I'm going to close out this issue. Please feel free to re-open if it's still happening to you.
