### ISSUE TITLE
Error: @vercel/edge-config: Network error 

### ISSUE THREAD

**Issue by Metarock** [vercel/storage#119]
### Environment information
```   Operating System:
      Platform: linux
      Arch: x64
      Version: #202303130630~1681329778~22.04~d824cd4 SMP PREEMPT_DYNAMIC Wed A
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 7.29.0
    Relevant packages:
      next: 13.4.0
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
```

### To reproduce

1. Use the latest Nextjs version app directory
2. use a `generateStaticParams` on a server component page `app/[id]/yourpage.tsx` using a edge-config SDK function, in my case the `get` call 

### Describe the bug
When building a static page in Nextjs with `generateStaticParams` that uses the edge-config SDK it spits out the following error
```error - node_modules/@vercel/edge-config/dist/index.node.js (1:1052) @ eval
error - Error: @vercel/edge-config: Network error
    at eval (webpack-internal:///(sc_server)/./node_modules/@vercel/edge-config/dist/index.node.js:46:23)
    at async Layout (webpack-internal:///(sc_server)/./app/sites/[site]/layout.tsx:25:20) {
  digest: undefined
}
null
```

### Expected behavior
I expect the edge-config SDK to not spit out an error.  For now as a work around  I have opted out from using the SDK client and go with the Vercel REST API for now as it seems to be working as expected `https://edge-config.vercel.com/your_edge_config_id_here/item/example_key_1?token=your_edge_config_read_access_token_here`

**Comment by dferber90** [comment]
We identified an issue in Next.js which is likely causing this. Will update here once a fix is out

**Comment by dferber90** [comment]
While the issue currently remains inside of Next.js, we temporarily added a workaround for this in https://github.com/vercel/storage/pull/157

It's available as `@vercel/edge-config@0.1.11`

**Comment by jeremieP** [comment]
Oh thanks @dferber90 ! 

Will test it this afternoon on my project, and make you a feedback if necessary.

UPDATE : Worked perfectly on my project ! Thanks again !

**Comment by danielbichuetti** [comment]
We have encountered this issue while utilizing Nuxt. 100% of the time.

**Comment by dferber90** [comment]
@danielbichuetti You've already pointed this out here https://github.com/vercel/storage/issues/95#issuecomment-1913282484.

In the future, please open a separate issue if you experience a problem instead of commenting on multiple closed issues as this makes it unnecessarily hard to help you resolve an issue and unnecessarily pings all people involved in the previous issues. Obrigado!

**Comment by danielbichuetti** [comment]
Sorry about that @dferber90. 

As most of the comments were from diff. people, except the team, thought about getting any hints from the guys who faced that in the last year.
