### ISSUE TITLE
@vercel/kv: Missing required environment variables KV_REST_API_URL and KV_REST_API_TOKEN

### ISSUE THREAD

**Issue by ffMathy** [vercel/storage#168]
Vercel KV works when running locally, but not when running from an edge function.

Here's my code:
```typescript
import { kv } from "@vercel/kv";

//the following is inside an Edge Function:
console.log("keys", await kv.keys("*"));
```

# My local setup (which works)
Ran the following commands:

```bash
vercel env pull .env.ssr.local
vite --mode ssr
```

When I invoke my function, it works just fine and sets the content in the KV store. I can verify this by going to the CLI in the Dashboard and checking that the key is there.

# My Vercel Edge Function setup (which doesn't work)
Pushed to my repo. 

Had Vercel deploy it. 

Verified in the build logs that both the function was deployed and the static assets:
<img width="983" alt="image" src="https://github.com/vercel/storage/assets/2824010/cd672f8f-5e22-45f1-a03b-c0d3cdabf693">

Verified that my database is attached to the project in the dashboard:
<img width="782" alt="image" src="https://github.com/vercel/storage/assets/2824010/8a277f56-ebbf-4795-bd3e-aa3c521be1fb">

After triggering the edge function, it returns an error 500. Viewing the logs yields the following error:

```
Error: @vercel/kv: Missing required environment variables KV_REST_API_URL and KV_REST_API_TOKEN
    at (@qwik-city-plan.js:27:78546)
    at (@qwik-city-plan.js:27:85712)
    at (assets/index.qwik-cc4e9f9f.js:9:5088)
    at (assets/index.qwik-cc4e9f9f.js:13:2233)
    at (assets/index.qwik-cc4e9f9f.js:7:1389)
    at (assets/index.qwik-cc4e9f9f.js:13:2161)
    at (assets/index.qwik-cc4e9f9f.js:13:2394)
    at (entry.vercel-edge.js:16:441)
    at (entry.vercel-edge.js:20:3149)
    at (entry.vercel-edge.js:20:830)
```

**Comment by ffMathy** [comment]
I just tried making my edge function return the following output:

```typescript
{ 
  url: process.env["KV_REST_API_URL"],
  env: process.env["VERCEL_ENV"]
}
```

I verified that these values are populated in the response that was returned to the client.

For obvious reasons I didn't try with my password etc 😏

**Comment by ffMathy** [comment]
Hmmm! Interesting...

The following *does not* work:

```typescript
{ 
  url: process.env.KV_REST_API_URL,
  env: process.env.VERCEL_ENV
}
```

This makes me suspect that this is related to Vite (which I am using to build the project). I think it tries to hide environment variables.

Although it's only supposed to do that in Development mode, from what I can read.

**Comment by ffMathy** [comment]
The following:

```typescript
{ 
  url: process.env.KV_REST_API_URL,
  env: process.env.VERCEL_ENV,
  url2: process.env["KV_REST_API_URL"],
  env2: process.env["VERCEL_ENV"],
  keys: Object.keys(process.env)
}
```

Yields this result:

```
{"url2":"redacted","env2":"production","keys":["VERCEL_REGION","VERCEL_ENV","KV_REST_API_READ_ONLY_TOKEN","KV_REST_API_TOKEN","KV_REST_API_URL","KV_URL","NX_DAEMON","TURBO_REMOTE_ONLY","VERCEL","VERCEL_ANALYTICS_ID","VERCEL_GIT_COMMIT_AUTHOR_LOGIN","VERCEL_GIT_COMMIT_AUTHOR_NAME","VERCEL_GIT_COMMIT_MESSAGE","VERCEL_GIT_COMMIT_REF","VERCEL_GIT_COMMIT_SHA","VERCEL_GIT_PREVIOUS_SHA","VERCEL_GIT_PROVIDER","VERCEL_GIT_PULL_REQUEST_ID","VERCEL_GIT_REPO_ID","VERCEL_GIT_REPO_OWNER","VERCEL_GIT_REPO_SLUG","VERCEL_URL","VERCEL_WEB_ANALYTICS_ID"]}
```

Note how `env` and `url` are not there, but `env2` and `url2` is.

Gotta check my build output it seems.

**Comment by ffMathy** [comment]
Found something: https://github.com/vitejs/vite/issues/3077

**Comment by vvo** [comment]
@ffMathy Thanks for the detailed report and investigation, do you think this is happening only in library mode?

Also, were you able to check this specific documentation? https://github.com/vercel/storage/tree/main/packages/kv#a-note-for-vite-users

Let us know!

**Comment by ffMathy** [comment]
@vvo you're welcome!

No, unfortunately I think it happens for all modes.

Both Vite and Rollup seem to have the same behavior, so I think the proposed "hack" in the attached PR is the best option.

Yes, I have read that part of the documentation, and it doesn't work for me.

I hope that helps elaborate a bit.

**Comment by vvo** [comment]
@ffMathy Going back to this, have you found a way to solve this without your current PR? Just being curious here thanks

**Comment by MiguelTrinca** [comment]
I think I'm having the same issues. 

After deploying my application in vercel, I'm encountering `Error: @vercel/kv: Missing required environment variables KV_REST_API_URL and KV_REST_API_TOKEN` 

However I'm not using vite but instead Next.js. 

This is my current code:
```typescript
import { kv } from "@vercel/kv";

const user = await kv.hgetall('user:me');
``` 

I've also tried with
```typescript
import { createClient } from "@vercel/kv";

const users = createClient({
    url: process.env.KV_PRD_REST_API_URL,
    token: process.env.KV_PRD_REST_API_TOKEN,
});
```

But with this code I'm having this `error:Type 'string | undefined' is not assignable to type 'string' ` in _url_ and _token_

**Comment by MiguelTrinca** [comment]
I was trying to bypass it using `import { createClient } from 'redis';`

I ran the code:
```typescript
        const kv = createClient({
            password: process.env.REDIS_PASS,
            socket: {
                host: process.env.REDIS_HOST,
                port: Number(process.env.REDIS_PORT)
            }
        });
``` 

It launched this error: `ClientClosedError: The client is closed`

**Comment by vvo** [comment]
@ffMathy news on this: I spent 30 minutes giving a try to the latest qwik + the vercel edge adapter. Good news: they support process.env natively now. Bad news: it's impossible to deploy on Vercel edge a qwik website using vercel/kv. Because vercel/kv depends on upstash/redis which depends on crypto-js which can't be bundled well with an error like `Cannot bundle Node.js built-in "crypto" imported from "node_modules/crypto-js/core.js"`.

Since this issue was about process.env, this is now solved. Now about Qwik not willing to deploy that's a different story and one for their repository. The complexity of JS app bundling (in this case: qwik + vite + rollup) makes it harder to fix these issues.

@MiguelTrinca can you open a different issue with a reproducible example? Thanks.

` error:Type 'string | undefined' is not assignable to type 'string' `. is a TypeScript error
