### ISSUE TITLE
Set Neon webSocketConstructor 

### ISSUE THREAD

**Issue by ghost** [vercel/storage#182]
I added support for @vercel/postgres in [authjs-adapter-sql](https://github.com/roelandmoors/authjs-adapter-sql).
It works, but I had to use the webSocketConstructor of the neon driver to get it working in Jest:
https://github.com/roelandmoors/authjs-adapter-sql/blob/main/tests/vercel.test.ts#L9

I also found something like this here:
https://github.com/vercel/storage/blob/main/packages/postgres/src/index-node.ts

Maybe @vercel/postgres should allow setting the websocket constructor directly? 
Or is there a better solution?

**Comment by vvo** [comment]
Hey @roelandmoors I see you archived your package, so closing this issue for now, thanks
