### ISSUE TITLE
import { sql } from '@vercel/postgres'; will never work with create-react-app

### ISSUE THREAD

**Issue by kanglicheng** [vercel/storage#211]
I think it's a foregone conclusion but just want to make sure I did not miss anything. If using CRA, all environment variables must be prefaced with REACT_APP so the no config option will always fail to pick up the required variables i.e. POSTGRES_URL. Is this correct?

**Comment by dferber90** [comment]
Yes that sounds correct. You'd need to explicitly pass the credentials in that case.
