### ISSUE TITLE
@vercel/postgres SELECT queries WHERE clause not handling values with symbols

### ISSUE THREAD

**Issue by amroczeK** [vercel/storage#229]
I originally posted this in the Vercel community discussion, but adding here for more visibility. @tcc-sejohnson 

### Summary

I am having trouble doing the following select statement using `import { sql } from "@vercel/postgres";` in my NextJs project.

Via CLI (psql) with the following command: 
`SELECT * FROM Guests WHERE address = '2/105 Seventh Ave, Maylands WA, Australia';` I get this result:
![image](https://github.com/vercel/community/assets/18630966/6f8b8f59-981d-4491-9ae7-a656ee11cf69)

I am unable to use the vercel postgres npm package to retrieve this data programattically in nextjs. I have tried the following examples in NextJs API route with no luck:

1. Following documented example https://vercel.com/docs/storage/vercel-postgres/sdk#sql
```
const { rows } = await sql`SELECT * FROM Guests WHERE address = ${address};`;
```

2. Adding apostophes around ${address} line in psql returns the following error:
```
const { rows } = await sql`SELECT * FROM Guests WHERE address = '${address}';`;
```
> error: bind message supplies 1 parameters, but prepared statement "" requires 0

3. Wrapping ${address} in double quotations returns this error:
```
const { rows } = await sql`SELECT * FROM Guests WHERE address = "${address}";`;
```
> error: column "$1" does not exist

4. Adding the address directly with apostohpes works and returns results
```
const { rows } = await sql`SELECT * FROM Guests WHERE address = '2/105 Seventh Ave, Maylands WA, Australia';`;
```

5. I have tried:
```
const query = "SELECT * FROM Guests WHERE address = '" + address + "';";
console.log(query); // SELECT * FROM Guests WHERE address = '2/105 Seventh Ave, Maylands WA, Australia';
const { rows } = await sql`${query}`;
```

What is the proper way to use `sql` from the SDK to query a table for a row that has a value which has a symbol e.g. addresses with a unit number?

I have also tried:
- Encoding the address
- Using escape squences
- Tried PSQL string functions

### Steps to Reproduce

1. Go to Vercel -> Storage and create a postgresql database
2. Create a table with a column called 'address'
3. Insert one row and populate the address column with a value of an address which is a unit/apartment e.g. `12/110 Mounts Bay Road,Perth, WA 6000`.
4. Try and retrieve that data using sql exposed by `import { sql } from "@vercel/postgres";` example docs: https://vercel.com/docs/storage/vercel-postgres/sdk

**Comment by elliott-with-the-longest-name-on-github** [comment]
The first option is the one that should work -- you didn't provide an error for it. Is it just returning nothing?

**Comment by amroczeK** [comment]
> The first option is the one that should work -- you didn't provide an error for it. Is it just returning nothing?

It was returning an empty row, I just tested it again and its working with my original implementation :| I kid you not it kept returning me an empty array as rows, indicating no data. Then I tried all the other options I mentioned to see if I was doing something wrong in the query.

I think maybe there was a syncing issue with the updates I made to the database and the instance of the database my application was querying for data.

Here is what originally happened:
1. Populated the DB withh some dummy data a day or so ago
2. Inserted a new row into the table, tested pulling the data from the application (all good)
3. Realised that the address was wrong e.g. `105 Seventh Ave, Maylands WA, Australia` instead of `2/105 Seventh Ave, Maylands WA, Australia` and edited the row in DBeaver and saved the change.
4. Using PSQL I inspected the rows on the table and verified that the change was saved.
5. Began trying to verify pulling the row from the application where I experienced issues and went down the rabbit hole.

I am not sure how the database is hosted or scaled in the cloud, maybe my application was connecting to an instance of my DB where its data wasn't yet consistent with the other instances.

But it is randomly working now, so i'll close the issue thanks.

Code reference:
```
// <comonent_name>.tsx
...
const params = { address: address };
const urlParams = new URLSearchParams(Object.entries(params));
const response = await fetch(`/api/guest?${urlParams}`, {
  method: "GET",
  headers: {
    "Content-Type": "application/json",
  },
});
...
```

```
// pages/api/guest.ts
import { sql } from "@vercel/postgres";
import { NextApiRequest, NextApiResponse } from "next";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const params = req.query;
  const address = Array.isArray(params.address)
    ? params.address[0]
    : params.address;

  try {
    const { rows, fields } =
      await sql`SELECT * FROM Guests WHERE address = ${address};`;

    if (!rows?.length) {
      return res.status(404).json({
        status: 404,
        message: "Not Found",
      });
    }
    res.status(200).json(rows);
  } catch (error: any) {
    console.error(error);
    res.status(error?.status || 500).json({ success: false, error });
  }
}

```

**Comment by johanlajili** [comment]
I just had the **exact** same issue : populating data manually, realising it is wrong today, updating it, but fetching from my client would return empty row.
Looking at yours and mine, it seemed clear that it was a cache issue, and I resolved it by deleting the content of the `.next/cache/fetch-cache` folder. After that the sql query worked as expected.
Leaving here for people having the same issue in the future.
