### ISSUE TITLE
@vercel/kv FEATURE REQUEST indexing

### ISSUE THREAD

**Issue by BibiSebi** [vercel/storage#246]
Dear Vercel team,

I wanted to take a moment to express my appreciation for the remarkable SDK you've developed. It has been a pleasure using it in my current project.

As I've been integrating KV storage into my application, I've noticed its impressive efficiency. However, I've encountered a common scenario where querying by more than just the key becomes necessary. This is where Redis and its FT commands shine. I was wondering if there are any plans to incorporate features such as FT.CREATE and FT.SEARCH into the SDK?

I hope I've provided enough context for my request. If you require any additional information, please don't hesitate to let me know. Thank you for your attention and for creating such a valuable tool.

**Comment by adriancooney** [comment]
Thanks for your kind words and feedback @BibiSebi! We do have plans to add support for RediSearch but unfortunately I can't offer a timeline right now. I've tracked your feedback internally on the feature request. Thanks!
