### ISSUE TITLE
`hset` does not accept 3rd argument (SetCommandOptions)

### ISSUE THREAD

**Issue by zipme** [vercel/storage#247]
When reading the documentation [here](https://vercel.com/docs/storage/vercel-kv/kv-reference#hset-example)

The example uses the following code:
```ts
await kv.hset(
      'userSession',
      { userId: 123, email: 'ex@example.com' },
      { ex: 100 },
    );
```

However,  the current function signature looks it only supports two arguments:
```ts
hset: <TData>(key: string, kv: {
        [field: string]: TData;
    }) => Promise<number>;
```

version:
```json
"@vercel/kv": "^0.2.2",
```

> Note the `set` function does accept `SetCommandOptions` as the 3rd argument

**Comment by adriancooney** [comment]
Thank you for the report @zipme. This was an error in our documentation and has been fixed. `@vercel/kv` API tracks Redis and [`HSET`](https://redis.io/commands/hset/) does not support options like `{ ex: 100 }`.
