### ISSUE TITLE
It appears that "import { sql } from '@vercel/postgres';" causes errors in production

### ISSUE THREAD

**Issue by 619** [vercel/storage#276]
I started a project consisting of a single API function that imports @vercel/postgres (import { sql } from '@vercel/postgres';
) where the only package I ever installed with npm was @vercel/postgres (npm i @vercel/postgres). It works on localhost when I run 'vercel dev', but when it is pushed to production on vercel, the API function fails with this error:

```
2023-07-11T14:55:44.204Z	undefined	ERROR	Cannot find module '/var/task/node_modules/@vercel/postgres/dist/index-node.cjs'
2023-07-11T14:55:44.204Z	undefined	ERROR	Did you forget to add it to "dependencies" in `package.json`?
RequestId: a4dc0c40-e5ff-4a94-befb-dbdc8198d56d Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by 619** [comment]
I am using ^0.4.0 version of @vercel/postgres (in package.json)

**Comment by adriancooney** [comment]
Thanks for the report @619. Before we can help, we'll need more context on the problem - ideally a minimal reproduction. We'll need to know things like:

* Node version
* Vercel CLI version
* The contents of the `package.json`
* The contents of the `vercel.json`, if any. (this is not related to your `.vercel` directory)
* Your file structure and an example of the API handler
* How you are deploying the code - via git or via `vercel deploy` command?

To best help us solve the issue here, an exact reproduction published to Github would be great.

**Comment by 619** [comment]
Sure, I can do that. Is there a private means of doing so? I'm not pushing my code to a public repo. It would be even better if I can authenticate/allow you to look at my project on vercel so you can see everything yourself. 

Node v: 18.16.0 (ran node -v locally)
Vercel CLI v: 29.3.1 
package.json:
```
{
  "name": "NAME",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@vercel/postgres": "^0.4.0",
    "eslint": "8.44.0",
    "eslint-config-next": "13.4.8",
    "next": "^13.4.8",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  }
}
```
vercel.json: I can show you privately.

**Comment by 619** [comment]
Oh yes, I forgot to mention that I generated this project from the nextjs clone template on vercel.

**Comment by 619** [comment]
Update: I created another repo using the nextJS template on vercel, copied my code from api/redirect.js and vercel.json, installed @vercel/postgres using npm, and I got the same error. @vercel/postgres does indeed break in production.

**Comment by 619** [comment]
The issue was that I was using an import statement in a serverless function.

I was using:
`import { sql } from '@vercel/postgres';`

when I should have been using:
`const { sql } = require('@vercel/postgres')`
