### ISSUE TITLE
@vercel/kv: reading from streams unsupported?

### ISSUE THREAD

**Issue by matty-southpawstudio** [vercel/storage#278]
Are streams supported? The documentation is misleading as [Redis compatibility page](https://vercel.com/docs/storage/vercel-kv/redis-compatibility#streams) says they are, but then [another page](https://vercel.com/docs/storage/vercel-kv/kv-reference) has no mention of streams.

In the KV CLI I was able to add into a stream, but I cannot read that data.

CLI fails with
> ERR Command is not allowed in REST: "XREAD"

There is no `xRead` method in the `@vercel/kv` package.

Upstash is [showing support](https://docs.upstash.com/redis/overall/rediscompatibility) for reading from streams, wondering how to access it KV?

**Comment by adriancooney** [comment]
Apologies @matty-southpawstudio, this should be clearer in the documentation. The `@vercel/kv` SDK does not support Streams yet and by extension, the CLI on the KV store page on the Vercel Dashboard. You must connect directly to the database server via modules like [ioredis](https://github.com/redis/ioredis) or [node-redis](https://github.com/redis/node-redis), or the `redis-cli` to use Streams.

Here is an example from the [Redis docs page](https://redis.io/docs/data-types/streams/):

```sh
$ redis-cli --tls -u redis://<snip>:<snip>@<snip>.kv.vercel-storage.com:34991
<snip>.kv.vercel-storage.com:34991> XADD temperatures:us-ny:10007 * temp_f 87.2 pressure 29.69 humidity 46
"1689152224222-0"
```

Thanks for opening an issue. I've added a note to the package's README with https://github.com/vercel/storage/issues/278.
