### ISSUE TITLE
Pass Kysely config to `createKysely`

### ISSUE THREAD

**Issue by boris-arkenaar** [vercel/storage#305]
I'd like to pass a plugin to Kysely, but it looks like that's not possible with the `createKysely` function in https://github.com/vercel/storage/blob/main/packages/postgres-kysely/src/index.ts.

I copied the code to my own code base and made the following changes to make it work.

```typescript
export function createKysely<T>(
  poolConfig?: VercelPostgresPoolConfig,
  kyselyConfig?: Partial<KyselyConfig>
): Kysely<T> {
  return new Kysely<T>({
    ...kyselyConfig,
    dialect: new VercelPostgresDialect({
      ...poolConfig,
      pool: createPool(poolConfig),
    }),
  });
}

```

Could this be incorporated into this library?

**Comment by rchaves007** [comment]
I ended up fixing this myself using just the VercelPool that vercel provides, this allows me to connect to vercel and add plugins

```
export const db = new Kysely<DB>({
  dialect: new PostgresDialect({
    pool: new VercelPool({
      connectionString: env.POSTGRES_URL,
    }),
  }),
  plugins: [new CamelCasePlugin()],
});
```

**Comment by vvo** [comment]
Hey there, I just opened a PR with your code @boris-arkenaar thanks a lot.

BTW, we're wondering if our kysely adapter is adding a lot of value versus maybe telling the community to use https://github.com/seveibar/kysely-neon. As user of Kysely, what do you think?

**Comment by boris-arkenaar** [comment]
Thanks for merging the change @vvo 

I didn't know about kysely-neon, will take a look.
