### ISSUE TITLE
feature request: be able to adjust the column width in postgres dashborad

### ISSUE THREAD

**Issue by aerinkim** [vercel/storage#320]
Hello Vercel team, I appreciate your work with the Postgres database within Vercel. It's more straightforward to use than Neon. I have a suggestion for a new feature. Right now, I can't change the width of the columns on the dashboard. Is there a way I can do this? Alternatively, a quick fix could be to allow users to download the data as a CSV file. The current situation is we can't see the full query result on Vercel without using Neon.

![Screen Shot 2023-08-03 at 9 41 59 AM](https://github.com/vercel/storage/assets/10659562/0c2e4e86-5c36-4ec6-aec0-1ade9d34a93d)

**Comment by correttojs** [comment]
hi @aerinkim , thanks for reporting the issue. I think both suggestions are meaningful, we'll evaluate the best option and work on it soon

**Comment by correttojs** [comment]
closing as the issue doesn't affect the storage SDK (we will work on the Vercel UI fix anyway)
