### ISSUE TITLE
Vercel KV: Support for Redis Time Series

### ISSUE THREAD

**Issue by roeekl** [vercel/storage#329]
Hi,
Is there any plan to add support for Redis Time Series? https://redis.io/docs/data-types/timeseries/

I know this is an external module but it would be great to have the option to user it.

**Comment by adriancooney** [comment]
Hi @roeekl. Thanks for reaching out and opening an issue. Unfortunately I don't have good news - Redis Time Series is not on our partner [Upstash's near or long term roadmap](https://roadmap.upstash.com/). If you feel strongly about your use-case, please reach out to our support with a feature request and detail your use-case. We'll track it internally and consider it among other priorities.
