### ISSUE TITLE
typo in doc

### ISSUE THREAD

**Issue by yiliang114** [vercel/storage#332]
![image](https://github.com/vercel/storage/assets/11473889/58e56d3c-0622-413f-a830-5aa6c550b5f3)

Where is the document warehouse related to storge? I tried to look for it but couldn't find it. Is there no open source?

**Comment by dferber90** [comment]
Thank you for reporting, this has been fixed <picture data-single-emoji=":frog-thumbsup:" title=":frog-thumbsup:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..0zlgg9XC-ozjjrMj.5cQkbGB54TkpYckvWv8Iyews4xyPRMnDEipReibg2Ic-VtCGAiCNu754_89t6P4N2lkYrWuP886O9nTpb2851aQKPkfN_RKnPpKC5u6vHn-90jBDYeI0_SpxTM9-eUp4HQU.EAAEqivBJmT9f3ISKjLvNg" alt=":frog-thumbsup:" align="absmiddle"></picture> 

https://vercel.com/docs/storage/vercel-postgres/quickstart#preparing-your-local-project
