### ISSUE TITLE
vercel db pool can not access envs in astro

### ISSUE THREAD

**Issue by alireza-constantin** [vercel/storage#349]
Hi everyone,

I'm trying to use Vercel Postgres with Drizzle and Astro. When I try to use the Vercel database pool with Drizzle, it looks like Vercel can't access the environment file and returns undefined. This causes the following error:

```
VercelPostgresError: 'missing_connection_string' - You did not supply a 'connectionString,' and no 'POSTGRES_URL' environment variable was found.
```

The code I'm using is:
```
import { drizzle } from "drizzle-orm/vercel-postgres";

import { sql } from "@vercel/postgres";

export const db = drizzle(sql);
```
I was able to solve the issue by changing how Vercel DB can access the environment. I did this by importing the loadEnv function from vite and using it to get the environment variables. Here is the updated code:
```
import { loadEnv } from "vite";
const env = loadEnv(process.env.NODE_ENV, process.cwd(), "");

// src/postgres-connection-string.ts
function postgresConnectionString(type = "pool") {
  let connectionString;
  switch (type) {
    case "pool": {
      connectionString = env.POSTGRES_URL;
      break;
    }
  }
  return connectionString;
}
```
I'm not sure if this is a Vite issue, an Astro issue, a Vercel Postgres issue, or something else. I'm also not sure if I'm doing something wrong or if there's something wrong with my computer. I would appreciate any help you can provide.

I'm using Astro 3.0.8 and my OS is Ubuntu 22.

**Comment by adriancooney** [comment]
Hello @alireza-constantin. Vite does not expose environment variables in `process.env` so they must be explicitly set in your config or you must manually create the KV client. See [A note for Vite](https://github.com/vercel/storage/tree/main/packages/postgres#a-note-for-vite-users) users on our README. Thank you for your report, hopefully other searchers will find this issue.
