### ISSUE TITLE
File stored in blob storage are not working

### ISSUE THREAD

**Issue by ramiel** [vercel/storage#407]
Hello. I enabled the blob storage and I'm able to correctly upload a file. The metadata inspector correctly reports the right file type and size. When I try to download though, I receive a broken file. Here an example: https://a6cow11td7ghinqu.public.blob.vercel-storage.com/orgs/logos/savethechildren-LgEp0fWH5UZmt7K0A2OkfN3guNPnQ2.jpg

**Comment by vvo** [comment]
Hey there @ramiel, could you send here the original file? And can you provide the code you're using to send the image to Vercel Blob? Thanks.

**Comment by ramiel** [comment]
Sure, the original file is the one attached in this comment.

This is the code

```ts
import { put } from "@vercel/blob";
import type { NextApiResponse, NextApiRequest } from "next";

export default async function handler(
  request: NextApiRequest,
  response: NextApiResponse
) {
  
  const blob = await put(
    `orgs/logos/${request.query.filename as string}`,
    request.body,
    {
      access: "public",
    }
  );
  return response
      .status(200)
      .json(blob);
}
```

![savethechildren](https://github.com/vercel/storage/assets/324687/532d6909-9872-4ac7-8276-26d4c34f5530)

**Comment by vvo** [comment]
@ramiel can you show the frontend code you're using to call this handler? I suspect request.body is not exactly what we think it is here.

**Comment by ramiel** [comment]
Yes sure. The relevant part is this function

```ts
const upload = useCallback(
    async ({ file, id }: { file: File; id: string }) => {
      const response = await fetch(
        `/api/organisation/upload?filename=${file.name}&id=${id}`,
        {
          method: "POST",
          body: file,
        }
      );

      
    },
    []
  );
```

that is called with 
```ts
      const input = inputFileRef.current;
      if (input) {
        const file = input?.files?.[0];
        if (file && id) {
          await upload({ file, id });
          input.value = "";
        }
      }
```

Is the body in the wrong format?

**Comment by ramiel** [comment]
The code is an adaptation of this example https://vercel.com/docs/storage/vercel-blob/quickstart#create-a-server-upload-page

**Comment by vpaul18** [comment]
@vvo  Also experiencing this.

**Comment by eleanorcare** [comment]
Same issue here when uploading from client side.
Moved to using AWS S3 instead..

**Comment by vvo** [comment]
Hey there, we're looking into this bug and will report tomorrow (Oct 3) about it

**Comment by vvo** [comment]
Hi everyone, we found the issue, this is a documentation issue. You are all possibly using [Pages API Routes](https://nextjs.org/docs/pages/building-your-application/routing/api-routes)?
If that's the case, then:

**First**, make sure you send a File to your upload route, like this:
```ts
const file = inputFileRef.current.files[0];

const response = await fetch(
  `/api/avatar/upload?filename=${file.name}`,
  {
    method: 'POST',
    body: file,
  },
);
```

**Second, and the most important part**, update your upload route like this:

```ts
import { put } from '@vercel/blob';
import { NextResponse } from 'next/server';

// ⚠️ The below code is for Pages API Routes only
export async function POST(request: Request): Promise<NextResponse> {
  const { searchParams } = new URL(request.url);
  const filename = searchParams.get('filename');

  const blob = await put(filename, request, { // The important change, not `request.body` but `request`
    access: 'public',
  });

  return NextResponse.json(blob);
}

// Another important change:
export const config = {
  api: {
    bodyParser: false,
  },
};
```

If you're still having issues displaying uploaded images in a webpage please open a different issue with details on:
- Which Next.js version you're using
- Pages API routes or App Router Route Handlers
- Frontend code you're using to send the file

Thanks all, happy uploading.

PS: We're in the process of updating all the examples on the website to acknowledge for this change. Also on behalf of Vercel, we're deeply sorry you spent a lot of time on this bug, our documentation was not correct here.

**Comment by ramiel** [comment]
Thanks @vvo . I will try later on today and I'll report back.

**Comment by ramiel** [comment]
Perfect, this works. Is there any other change in case the function is running on the edge runtime?

**Comment by vvo** [comment]
@ramiel yes there would be changes for edge runtime + Pages API Routes, see:

```ts
import { put } from "@vercel/blob";
import type { NextApiResponse, NextApiRequest, PageConfig } from "next";
import { NextResponse } from "next/server";

export default async function handler(
  request: Request
) {
  const { searchParams } = new URL(request.url);
  const filename = searchParams.get("filename");

  const blob = await put(filename, request.body, {
    access: "public",
  });

  return NextResponse.json(blob);
}

export const config: PageConfig = {
  runtime: "edge",
};
```

We're back to request.body in this case, not request.
I would suggest you switch to the app router routes when you can as they provide an isomorphic signature (edge/non-edge) along with being the new default for our documentation examples.

**Comment by sahanxdissanayake** [comment]
@vvo keen to dig in to this issue a bit as I have the issue that's attached above :/

**Comment by sahanxdissanayake** [comment]
update: Moved to AWS S3 and langchain is working as expected

**Comment by vvo** [comment]
@sahanxdissanayake we provided an update and updated all documentation, which issue did you have initially? Can you add more details?

Create a new issue if necessary. The answer was here: https://github.com/vercel/storage/issues/407#issuecomment-1744666914

**Comment by sahanxdissanayake** [comment]
I'm not sure of the reason @vvo but to recreate the issue I'd ask you to try the following code.

```python
import pandas as pd

# Read the CSV file - error happens here
data = pd.read_csv("https://link-to-vercel-public-csv-file")
```

https://www.datacamp.com/tutorial/pandas-read-csv

**Comment by vvo** [comment]
Hey @sahanxdissanayake I am not following how your code relates to Vercel Blob, can you explain it more? Thank you

**Comment by a2thek26** [comment]
> Hey @sahanxdissanayake I am not following how your code relates to Vercel Blob, can you explain it more? Thank you

Having the same issue when trying to load a csv from a vercel blob url. It gives a 403. When I go directly to the url, it downloads but not when referenced using pandas.

**Comment by vvo** [comment]
@a2thek26 and @sahanxdissanayake this seems specific to panda read_csv. Can you check this answer: https://stackoverflow.com/questions/62278538/pd-read-csv-produces-httperror-http-error-403-forbidden

It seems that panda is making HTTP request in a way that Cloudflare doesn't like. Try with the provided solutions and see if this works.

**Comment by Zathet12** [comment]
Hey, am using next 13.1 some fix to this?

**Comment by vvo** [comment]
@Zathet12 Please open a new issue with more details about your problem, for us to be able to reproduce it. Thanks!
