### ISSUE TITLE
Postgresql DB writes stopped at 132170 entries in a table. Where are logs for db?

### ISSUE THREAD

**Issue by ctrenks** [vercel/storage#421]
I see blob storage logs are in the Vercel logs but no logging for PostgreSQL that I can find?

**Comment by ctrenks** [comment]
writing to database via php with PDO and everything appears correct as it added 133K+ but stopped with this entry that has no obvious issues?

INSERT INTO casino_p_games_image 
(game_image_id,game_image_url,game_image_alt_text,game_image_name,game_image_parent,game_image_position,w,h,tw,th) 
VALUES 
(:game_image_id,:game_image_url,:game_image_alt_text,:game_image_name,:game_image_parent,:game_image_position,:w,:h,:tw,:th) 

Params: 10 
Key: Name: [14] :game_image_id 		paramno=0 name=[14] ":game_image_id" is_param=1 param_type=2 
Key: Name: [15] :game_image_url 	paramno=1 name=[15] ":game_image_url" is_param=1 param_type=2 
Key: Name: [20] :game_image_alt_text 	paramno=2 name=[20] ":game_image_alt_text" is_param=1 param_type=2 
Key: Name: [16] :game_image_name 	paramno=3 name=[16] ":game_image_name" is_param=1 param_type=2 
Key: Name: [18] :game_image_parent 	paramno=4 name=[18] ":game_image_parent" is_param=1 param_type=2 
Key: Name: [20] :game_image_position 	paramno=5 name=[20] ":game_image_position" is_param=1 param_type=2 
Key: Name: [2] :w 			paramno=6 name=[2] ":w" is_param=1 param_type=2 
Key: Name: [2] :h 			paramno=7 name=[2] ":h" is_param=1 param_type=2 
Key: Name: [3] :tw 			paramno=8 name=[3] ":tw" is_param=1 param_type=2 
Key: Name: [3] :th 			paramno=9 name=[3] ":th" is_param=1 param_type=2

    [:game_image_id] => 134497
    [:game_image_url] => 9-stars-dice5040684.jpg
    [:game_image_alt_text] => Three of a Kind win
    [:game_image_name] => 9-stars-dice5040684.jpg
    [:game_image_parent] => 17062
    [:game_image_position] => 6
    [:w] => 1680
    [:h] => 1008
    [:tw] => 0
    [:th] => 0

**Comment by ctrenks** [comment]
ahh solved the issue, was a forein key issue not an insert issue,

**Comment by correttojs** [comment]
we are planning to provide better observability tools for postgres too
