### ISSUE TITLE
@vercel/blob - await onUploadCompleted

### ISSUE THREAD

**Issue by errorsmyown** [vercel/storage#444]
A question rather than an issue (hope that's ok!)...

I have a Next application and I've created a client upload route as per the sdk docs, using the `upload()` method in my client component, and have it working locally using ngrok as recommended. I'm using `onUploadCompleted` to update my database, storing a new record with the `blob.url` and some other data created at that stage. This is all working great :)

Once the upload is fulfilled, for updating my client component UI, I'm interested in additional data queried from my database that was created during `onUploadCompleted` (not just the json returned by `upload()`). Is it possible to know client side when `onUploadCompleted` has been successful?

Any advice much appreciated, many thanks.

**Comment by vvo** [comment]
@errorsmyown Do you mean you'd like to send back data from `onUploadCompleted` back to the client call of upload? Something like:

```
const blobWithData = upload(...)
console.log(blobWithData.userName); // => "errorsmyown"
```

?

Otherwise, as for
> for updating my client component UI, I'm interested in additional data queried from my database that was created during onUploadCompleted

We recommend you do something like this:

```
const blob = await upload();
const moreData = await queryYourApi(blob.url);
```

**Comment by ernanibmurtinho** [comment]
> A question rather than an issue (hope that's ok!)...
> 
> I have a Next application and I've created a client upload route as per the sdk docs, using the `upload()` method in my client component, and have it working locally using ngrok as recommended. I'm using `onUploadCompleted` to update my database, storing a new record with the `blob.url` and some other data created at that stage. This is all working great :)
> 
> Once the upload is fulfilled, for updating my client component UI, I'm interested in additional data queried from my database that was created during `onUploadCompleted` (not just the json returned by `upload()`). Is it possible to know client side when `onUploadCompleted` has been successful?
> 
> Any advice much appreciated, many thanks.

Can you share how did you manage to make the onUploadCompleted work?
I tried, but it's not entering, the whole handleupload function works, but not at this step.
