### ISSUE TITLE
Update upstash-redis version

### ISSUE THREAD

**Issue by borjadotai** [vercel/storage#445]
Seems like you guys are using @upstash-redis version 1.22.0 on `kv`. This version uses a default deserialize that applies JSON.parse to everything without checking the actual data type. 

This means that when you for example use the ai chat template project and change the auth to use google which uses large number user sub / ids, the numbers are too big and they get rounded on that deserialize process breaking the chat history functionality.

Here's a link on issue with the @upstash team for more info: https://github.com/upstash/upstash-redis/issues/699

**Comment by borjadotai** [comment]
Nice one! Thanks 😉

**Comment by vvo** [comment]
Thanks for opening the issue @borjadotai 🙏
