### ISSUE TITLE
@vercel/postgres data deletion not working

### ISSUE THREAD

**Issue by discoverlance-com** [vercel/storage#472]
I have the following data in my database:
![image](https://github.com/vercel/storage/assets/52635726/f5a89e6a-ea00-4866-84b6-4ada9801a748)

I want to delete the data but generally, I will save data with slugs that are similar to the slug pattern in the above data. So I am writing a delete query that's supposed to delete data with that pattern. I run the following query both with this library and on the vercel dashboard but it does not work. When I run the query, it does not fail but the data is not deleted.
```ts
await sql`DELETE FROM notes 
  WHERE slug LIKE 'test-lorem-playwright-test-note-%';`;


// this is my table
await sql`
        CREATE TABLE IF NOT EXISTS notes (
            id SERIAL PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            slug VARCHAR(255) UNIQUE NOT NULL,
            description TEXT,
            "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    `;
```

**Comment by luismeyer** [comment]
hey @discoverlance-com,
i think there is a typo in the slugs in your db. The slugs in you db are missing the `y` of playwright. If you are still experiencing problems with your query, feel free to open another issue or contact the vercel support directly
