### ISSUE TITLE
Support `xrevrange` in @vercel/kv

### ISSUE THREAD

**Issue by notwedtm** [vercel/storage#477]
According to the [documentation](https://vercel.com/docs/storage/vercel-kv/redis-compatibility#unsupported-commands), `XREVRANGE` is supported, but it's not defined in `@vercel/kv`:

```
Property 'xrevrange' does not exist on type 'VercelKV'. Did you mean 'xrange'?ts(2551)
zmscore-10fd3773.d.ts(3011, 5): 'xrange' is declared here.
```

**Comment by gillyb** [comment]
It seems like Vercel wraps the @upstash/redis (https://github.com/upstash/upstash-redis) library, and they don't support it, even though they claim they do too. I guess some mistake, but you should probably open an issue on their repo

**Comment by adriancooney** [comment]
Thanks for the report @notwedtm. I'll forward this on to Upstash.

**Comment by adriancooney** [comment]
We can continue the discussion at https://github.com/upstash/upstash-redis/issues/349#issuecomment-1856117653. Closing this out since no more action required. I will check that we have upgraded to the latest `@upstash/redis`.
