### ISSUE TITLE
Just porgramming for the hobby project and have some fundamental issue of understanding vercel kv philosophy

### ISSUE THREAD

**Issue by CarloCornacco** [vercel/storage#493]
I am using redis - VERCEL KV to fetch the database to the main server component. Then In some client components databse is updated and sent back to Redis - it works. I have chcecked it in CLI, but the problem is NEXT/Vercel KV is showing all the time the old data (before update). The only way to update the database with a new value is to deploy it to production (it will update during build time). How to make it work for the NEXT server component to upload the REDIS DATA each new session? This is where I fetch data:

```js
import { kv } from "@vercel/kv";
async function getData() {

 const fileContents = await kv.json.get('bazaofert','$');

 return fileContents;

  }
```

this is the route.js, where I update the data and I would like NEXT to fetch this updated data at the start of the new session.
 
```js
export async function POST(req) {

 
 const data = await req.json()
 
   console.log('data',data)


return kv.json.set('datas','$[0].rating','6').then((promise)=>{return Response.json(promise)}).catch((err)=>{return Response.json('error)}

}
```

Thank You very much!
Karol

**Comment by luismeyer** [comment]
Hey @CarloCornacco 👋 ,

I can't quit understand your example code (maybe I just don't know enough redis). You read from the `bazaofert` key but you write to `datas` key. Is that expected?

The behaviour your describing does sound weird though. Did you maybe configure your project to be statically exported? I guess that could be a reason your data is only fetched on build.

You could have a look at this starter repo: https://github.com/vercel/examples/tree/main/storage/kv-redis-starter. Maybe you can find the difference to your implementation there. 
If none of this helps, it would be great if you could share an example repository which reproduces this issue, so we can help you debug further.

**Comment by CarloCornacco** [comment]
Thanks Luis for the answer,

I have read in the meantime that all the server fetches are cached forever by NEXT, so I have to revalidate it somewhere (now it works the database is being refreshed with the new session).

Yes, that is a mistake you are right (I pasted in the wrong fragment of code). Anyhow the convention is to fetch the database in the server component from redis, and send it as a prop to the client components for being modified.

```js
import { kv } from "@vercel/kv";
async function getDatas() {

const fileContents = await kv.json.get('datas','$');

return fileContents;

  }
```

this is the route.js, where I update the data and I would like NEXT to fetch this updated data at the start of the new session.

```js
export async function POST(req) {

const data = await req.json()

   console.log('data',data)

return kv.json.set('datas','$[0].rating','6').then((promise)=>{return Response.json(promise)}).catch((err)=>{return Response.json('error)}

}
```

**Comment by luismeyer** [comment]
great 👍  I'll close this issue, if you have any other problems feel free to open a new issue
