### ISSUE TITLE
Throws error when configured custom env name on initial setup of Vercel Postgres

### ISSUE THREAD

**Issue by devjiwonchoi** [vercel/storage#508]
Currently, the env name for PSQL should start as `POSTGRES_`, but the initial configuration for the PSQL on Vercel allows us to modify the default env name.

![Screenshot 2023-12-02 at 12 32 12 AM](https://github.com/vercel/storage/assets/120007119/c2432297-ec5e-4c89-8e67-606820b40949)

For example, I've modified it as `PSQL_`, and it is giving me the error after running `vercel env pull .env.development.local`:

`VercelPostgresError: VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.`

**Comment by correttojs** [comment]
hey @devjiwonchoi , did you try using the `createClient` method passing a [custom connection string](https://vercel.com/docs/storage/vercel-postgres/sdk#createclient)?

**Comment by devjiwonchoi** [comment]
@correttojs Nope, so if we use the advanced options of modifying env variable prefix, using `createClient` is mandatory in this case?

**Comment by correttojs** [comment]
> @correttojs Nope, so if we use the advanced options of modifying env variable prefix, using `createClient` is mandatory in this case?

yes, but we'll evaluate to expose another function to set a custom environment variable without using the `createClient`

**Comment by devjiwonchoi** [comment]
Sounds great. Thank you!
