### ISSUE TITLE
Blob PDF Support

### ISSUE THREAD

**Issue by jferrel7** [vercel/storage#509]
Hi - I'm evaluating Vercel Blob for usage in a project, so I've been uploading and testing with different file types. Images uploaded to Blob render when using img or the NextJS Image component. Video files successfully play in a video tag. However when I upload a PDF to blob, and use iframe, embed or object HTML tags to render, the PDF is downloaded to my computer instead of being viewable inline on my HTML document. Is there a supported way to display PDFs from blob on a HTML page?

**Comment by PeytonCleveland** [comment]
Having the same issue, iFrame and embed both start a download.

**Comment by correttojs** [comment]
hey, the issue is on our roadmap, we are planning to allow embedding more mime types soon

**Comment by jferrel7** [comment]
glad to hear, thanks for sharing

**Comment by PeytonCleveland** [comment]
In the meantime, a quick workaround is to create a route handler to use as the source to embed PDFs:

```javascript
import { getAuth } from "@clerk/nextjs/server";
import { eq } from "drizzle-orm";
import db from "@/db";
import { SourceDocument } from "@/db/schema";
import { NextRequest } from "next/server";

export async function GET(
  request: NextRequest,
  { params }: { params: { documentId: string } }
) {
  // Validate user is logged in
  const { userId } = getAuth(request);

  if (!userId) {
    throw new Error("Unauthorized");
  }

  const id = params.documentId;

  // Fetch document from db
  const document = await db
    .select()
    .from(SourceDocument)
    .where(eq(SourceDocument.id, id));

  // Fetch file from blob storage
  const blobResponse = await fetch(document[0].blobUrl!);

  // Return file
  return new Response(blobResponse.body, {
    status: blobResponse.status,
    statusText: blobResponse.statusText,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": "inline",
    },
  });
}
```

**Comment by vvo** [comment]
@PeytonCleveland @jferrel7 the latest release of `@vercel/blob` creates pdf files with an `inline` content-disposition, allowing you to display them as you wish 👍

**Comment by mfts** [comment]
That's very nice @vvo 👏

**Comment by vvo** [comment]
@mfts AND we're working on a feature where you can add ?download=1 to any blob URL and it will force downloading the file. This will be the best of both worlds: you can show a pdf preview (page, or new tab directly) AND you can create a download link directly to them also (useful in many cases instead of asking customer to "right click, save as").

WDYT?

**Comment by jferrel7** [comment]
@vvo that will be a great feature!

**Comment by mfts** [comment]
> you can add ?download=1 to any blob URL

Wouldn't that allow anyone else to add the `?download=1` param and download the file even if that's not intended?

**Comment by vvo** [comment]
> Wouldn't that allow anyone else to add the ?download=1 param and download the file even if that's not intended?

@mfts If you can open or display a PDF file in your browser, you can download it already (save as). Adding `?download=1` is only a way to create download URLs for developers using Vercel Blob explicitly rather than you having to go through weird proxying to make it happen.

Is that ok for you?

**Comment by mfts** [comment]
You're right. That's fine then. I like the addition of the url param 👍
