### ISSUE TITLE
@vercel/kv kv.get() seems to not get the latest result that is set by kv.set()

### ISSUE THREAD

**Issue by michjun** [vercel/storage#510]
It seems like kv.get() is caching the results and not getting the latest and I don't know how to make it work.

I have the following code, basically trying to check if a kv pair is already in the kv store, if yes, return the value; and if not, set it. However, the console.log in the last line always returns `null`, even if I go to the CLI and can see that the value is correctly set. 
```
const keyResults = await kv.get(key);
if (keyResults) return keyResults;

await kv.set(key, "asdf", {ex: 24 * 60 * 60});
console.log(await kv.get(key));
```

If I remove the first two line and just do the following, it seems like kv.get is able to get the correct value `asdf`
```
await kv.set(key, "asdf", {ex: 24 * 60 * 60});
console.log(await kv.get(key));
```

Also, and key that I've get previously, will not return the new value even if it is in different requests and if I restart my local development. Please advice on how I can invalidate the cache on redis cache 😅

**Comment by TKenneweg** [comment]
I have a very similar issue

```
'use server'
import { kv } from '@vercel/kv';
export async function logChat(text:string){
    let n_usage  = await kv.get('n_usage') ;
    console.log(n_usage)
}

```

always reads 5 from the database! No matter whats actually in it. The same code gives correct results if used in a route.ts file. Help please ^^

Edit: The numbers which I print with console.log appear yellow. Does this indicate a cache hit?

**Comment by dferber90** [comment]
It's hard to say without more context, but it could be that you're running into Next.js statically building the page, so the value present at build time will be used for every request, no matter if the value changed after the build.

- https://nextjs.org/docs/app/building-your-application/rendering/server-components#server-rendering-strategies
- https://nextjs.org/docs/app/building-your-application/caching#static-and-dynamic-rendering

One way to force them to be dynamic would be to call `unstable_noStore` ([docs](https://nextjs.org/docs/app/api-reference/functions/unstable_noStore))

```js
import { unstable_noStore as noStore } from 'next/cache';

'use server'
import { kv } from '@vercel/kv';
export async function logChat(text:string){
    noStore()
    let n_usage  = await kv.get('n_usage') ;
    console.log(n_usage)
}
```

**Comment by IksGarG** [comment]
> It's hard to say without more context, but it could be that you're running into Next.js statically building the page, so the value present at build time will be used for every request, no matter if the value changed after the build.
> 
>     * https://nextjs.org/docs/app/building-your-application/rendering/server-components#server-rendering-strategies
> 
>     * https://nextjs.org/docs/app/building-your-application/caching#static-and-dynamic-rendering
> 
> 
> One way to force them to be dynamic would be to call `unstable_noStore` ([docs](https://nextjs.org/docs/app/api-reference/functions/unstable_noStore))
> 
> ```js
> import { unstable_noStore as noStore } from 'next/cache';
> 
> 'use server'
> import { kv } from '@vercel/kv';
> export async function logChat(text:string){
>     noStore()
>     let n_usage  = await kv.get('n_usage') ;
>     console.log(n_usage)
> }
> ```

Worked great! But i decided to instead not force it like that, and went reading in the documentation of next.js. 
My solution was there all the time and it was simple as adding `{cache: 'no-store'}` in my dynamic fetch:

`dashboard/[slug]/page.jsx`
```js
useEffect(() => {
    const handleGetJob = async () => {
      if (!params.slug) return
      try {
        const response = await fetch(`/api/mockdatagetone/${params.slug}`, {
          method: 'GET',
          cache: 'no-store', // Added This!
        })
        const jobData = await response.json()
        setJob(jobData) // Store job data in state
      } catch (error) {
        console.error('Failed to fetch job:', error)
      }
    }
    handleGetJob()
  }, [params.slug])
```

Hope this helps someone else
