### ISSUE TITLE
vercel/kv exposes MULTI but not WATCH

### ISSUE THREAD

**Issue by djalilhebal** [vercel/storage#511]
Is there a way to use the `WATCH` command in Redis transactions (like `kv.multi().watch(someKeys)...`)?

**Comment by djalilhebal** [comment]
I was thinking of using `eval` and making the script invoke `redis.call('WATCH', ...)`, but this feels super hacky, and I'm not even sure if it will work as expected or if there are (practical or technical) downsides.

**Comment by romeovs** [comment]
It seems like `@upstash/redis` does not support this and nor is it planning to.
`@vercel/kv` is based on upstash so I don't think they can implement it either.

_Note: I'm not affiliated with Vercel or Upstash, but I was running into this issue myself recently._

**Comment by adriancooney** [comment]
Thank you @romeovs, you are correct. You can always connect to your Vercel KV using another library like `ioredis` which will support `WATCH`.
