### ISSUE TITLE
@vercel/postgres - can't do 'SELECT x WHERE id IN' query 

### ISSUE THREAD

**Issue by gillyb** [vercel/storage#514]
I need to do a SELECT IN query - to select multiple rows, but can't seem to do it. I tried many ways -

```
const ids = ['aaa', 'bbb', 'ccc'];
const {rows} = sql`select * from my_table where id in (${ids})`;
```
I also tried concatenating the ids on my own, but it also doesn't seem to work.

How would I execute a query like this ?

**Comment by elliott-with-the-longest-name-on-github** [comment]
Right now, you'll have to fall back to creating the query and calling `sql.query` yourself -- SQL templating is very limited:

```ts
const query = 'SELECT * FROM users WHERE id IN ($1, $2, $3)'
const params = [1234, 2345, 3456]
await sql.query(query, params)
```

However, when/if #504 merges, something like this will be possible:

```ts
await sql`SELECT * FROM users WHERE id IN (${LIST(params)})`
```

So hopefully you don't have to manually build more-complex queries for too long!

**Comment by gillyb** [comment]
That _TQL_ syntax looks great, would happy to see it merged.  
For now, thanks a lot for the response, I appreciate it :)
