### ISSUE TITLE
How to delete an entry in Vercel KV?

### ISSUE THREAD

**Issue by RayRemnant** [vercel/storage#528]
The documentation mentions setting and getting entries, but nothing about deleting. Is there an automatic expiration?
It seems that Redis has a delete capability. I'm new to it, so maybe I'm missing something out, but it does feel strange to me.

**Comment by elliott-with-the-longest-name-on-github** [comment]
Have you tried `kv.del`?

**Comment by RayRemnant** [comment]
Works! Thank you. It just felt weird to me that there was no mention for delete operations in the documentation.
