### ISSUE TITLE
Cannot delete blob database

### ISSUE THREAD

**Issue by andrewdku** [vercel/storage#536]
- Just to explore it, I created a Vercel Blob store. It's currently empty:

<img width="945" alt="image" src="https://github.com/vercel/storage/assets/140819896/daef7157-a010-4d18-a960-a1420d091608">

- However, I can't delete it despite it not having a single blob.

<img width="941" alt="image" src="https://github.com/vercel/storage/assets/140819896/a53df11e-8b14-4b67-9cc5-d88d5f45b73e">

**Comment by luismeyer** [comment]
hey @m1-dev,

this seems like a bug in the Vercel platform not in the `@vercel/blob` sdk. If you still see the issue please reach out to our support here: https://vercel.com/help. This way we can have a closer look at your store and help you solve the issue

**Comment by andrewdku** [comment]
> hey @m1-dev,
> 
> this seems like a bug in the Vercel platform not in the `@vercel/blob` sdk. If you still see the issue please reach out to our support here: https://vercel.com/help. This way we can have a closer look at your store and help you solve the issue

Okay, thank you. I didn't know where to put this issue.
