### ISSUE TITLE
Vercel Blob: Access denied, please provide a valid token for this resource

### ISSUE THREAD

**Issue by Falowo** [vercel/storage#541]
This issue comes when I use the client upload for files up to 500Mb. I have tried everything I read about this issue but I still have the issue. Actually it was solved some days ago but the issue came back after several days without uploading big files.

 // video-uploader.tsx
const filepath = !!postId
            ? `${newPost.userId}/${postId}/${file.name}`
            : `${newPost.userId}/temp/${file.name}`;

          const newBlob = await upload(filepath, file, {
            access: "public",
            handleUploadUrl: "/api/blob/video/upload",
            // clientPayload: user.id, // optional
          });

// /api/blob/video/upload/route.ts

import { handleUpload, type HandleUploadBody } from "@vercel/blob/client";
import { NextResponse } from "next/server";

export async function POST(request: Request): Promise<NextResponse> {
  const body = (await request.json()) as HandleUploadBody;
  console.log("in the route /api/blob/video/upload/route.ts");
  const validUntil: number = Date.now() + 1000 * 60 * 3; //  3 minutes

  try {
    const jsonResponse = await handleUpload({
      body,
      request,
      onBeforeGenerateToken: async (
        pathname: string,
        // clientPayload?: string // optional, sent from the client
      ) => {
        // Generate a client token for the browser to upload the file
        // ⚠️ Authenticate and authorize users before generating the token.
        // Otherwise, you're allowing anonymous uploads.

        // console.log("pathname", pathname);

        return {
          allowedContentTypes: [
            "video/mp4",
            "video/quicktime",
            "video/x-m4v",
            "video/*",
            "video/x-msvideo",
            "video/x-ms-wmv",
            "video/x-flv",
            "video/webm",
            "video/3gpp",
            "video/3gpp2",
            "video/ogg",
            "video/x-matroska",
          ],
          validUntil, // optional, in ms, default 30s setted at 60s
          tokenPayload: JSON.stringify({
            // optional, sent to your server on upload completion
            // userId: user.id!,
          }),
        };
      },
      onUploadCompleted: async ({ blob, tokenPayload }) => {
        // Get notified of client upload completion
        // ⚠️ This will not work on `localhost` websites,
        // Use ngrok or similar to get the full upload flow

        console.log("blob upload completed", blob, tokenPayload);

        try {
          // Run any logic after the file upload completed
          // const { userId } = JSON.parse(tokenPayload!);
          // console.log("userId", userId);
          // await db.update({ avatar: blob.url, userId });
        } catch (error) {
          throw new Error("Could not upload video");
        }
      },
    });

    return NextResponse.json(jsonResponse);
  } catch (error) {
    return NextResponse.json(
      { error: (error as Error).message },
      { status: 400 } // The webhook will retry 5 times waiting for a 200
    );
  }
}

**Comment by vvo** [comment]
@Falowo We just released (1 minute ago!) an experimental version of Vercel Blob to allow for big files upload, would you like to try it? Here's how:

```sh
pnpm add @vercel/blob@0.17.0-c2239f49-20231218111237
```

```ts
const newBlob = await upload('file.mp4', file, {
  access: "public",
  handleUploadUrl: "/api/blob/video/upload",
  multipart: true,
});
```

Let me know how it goes 👍

**Comment by Falowo** [comment]
I tried but the error is still there ...

**Comment by vvo** [comment]
@Falowo Can you try and remove the allowedContentTypes option? It may be the issue here.

**Comment by Falowo** [comment]
@vvo It solved partially the problem. The file is registered on my blob but it doesn't send back the response to my client upload-video.tsx. So On the web site the upload behave like not working. Should I restore the previous @vercel/blob version ?

**Comment by vvo** [comment]
@Falowo Yes try the previous version too, indeed. Also, did you make sure the file you were trying to upload was allowed as per the list of allowedContentTypes? It's weird that this is working after removing allowedContentTypes. Thanks!

BTW, about:
> Actually it was solved some days ago but the issue came back after several days without uploading big files.

Would you have some more precisions like timing when it started to fail/work? Thank you 🙏

**Comment by vvo** [comment]
@Falowo Did you change handleUploadUrl? It should be your old value "/api/blob/video/upload"

**Comment by Falowo** [comment]
I didn't change UploadUrl.  I'm sure the content type is video/mp4. I dont know the exact time it started to fail because I stoped uploading big files to save cost about 5 days ago. I will try to give you the exact time  I'm sure it was working perfectly as soon as possible

**Comment by vvo** [comment]
@Falowo I did multiple tests right now:
- files up to < 500mb are working using regular or multipart put and receive the complete webhook
- files >= 500 MB are working using multipart put and receive the complete webhook
- I tested the current version of blob package and the experimental version I shared with you, on the production Vercel Blob API

Not sure what's going on here for you so if you find the root cause happy to learn more about it 👍

**Comment by Falowo** [comment]
@vvo thanks for your help before. I found later that I had the response when I remove the allowedContentTypes option.
It's just that I had removed a setIsLoding(false) in my video-uploader.tsx. So the root of the problem is this option allowedContentTypes option. So I removed it and I'm checking the file.type on the video-uploader.tsx. The strange thing is that I tested it with the option allowedContentTypes  with image/png and it works perfectly for images. Also I'm sure that my video are "video/mp4" so I let the rest to you

**Comment by vvo** [comment]
@Falowo Thanks, what's the extension of the file you're trying to upload as mp4? You have to know that allowedContentTypes checks are done on the file extension, so if you do:

```
put('file.mkv', mp4File, {}); 
```

Then it will fail, because we will do a check on "file.mkv" and compare "mkv" with allowedContentTypes which is gonna fail.

**Comment by Falowo** [comment]
it's .mp4

**Comment by vvo** [comment]
@Falowo I was able to reproduce it, thanks a lot we're gonna investigate it

**Comment by vvo** [comment]
We have a fix that will be released very soon, thanks

**Comment by vvo** [comment]
In the meantime @Falowo just add "application/mp4" to your list of allowed content types

**Comment by vvo** [comment]
This has been released, you should no more get these errors, thanks

**Comment by vvo** [comment]
For everyone here, since this was a well followed ticket, I wanted to raise your awareness on an upcoming change we'd like to do on Vercel Blob SDK: no more random suffixes by default. Please join the conversation here:
https://x.com/vvoyer/status/1854816275173634175
