### ISSUE TITLE
Support for Signed URLs in Blob

### ISSUE THREAD

**Issue by minodisk** [vercel/storage#544]
I would like to see support for signed URLs under the assumption that `access: 'private'` is supported.
This is a feature that allows access to private files with a signed URL.

I think this feature is very useful when there is support in GCP and AWS to allow access to files that are confidential.

- [Signed URLs  \|  Cloud Storage  \|  Google Cloud](https://cloud.google.com/storage/docs/access-control/signed-urls)
- [Sharing objects with presigned URLs \- Amazon Simple Storage Service](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html)

**Comment by vvo** [comment]
Hey @minodisk thanks for the message, we want to provide a similar feature, yes here's our thinking:
- signed URLs are different than private blobs, signed URLs are just public blob urls with a TTL
- we want to offer true private blobs where, when upload with `access: 'private'` they won't have a URL associated and the only way to download them will be via a call to the API using your token

What do you think?

_PS: We may provide signed urls but we think it's a different feature_

**Comment by minodisk** [comment]
> signed URLs are just public blob urls with a TTL

I understand your idea. I'm looking forward to seeing it implemented.

BTW, I like the feeling of a world where everything exists in Vercel.

**Comment by KukretiShubham** [comment]
> we want to offer true private blobs where, when upload with access: 'private' they won't have a URL associated and the only way to download them will be via a call to the API using your token

@vvo hi, is this available now?

**Comment by Apoyoescolarrv** [comment]
@vvo Hi, any updates about this?

**Comment by theianzhang** [comment]
Hey all, any updates? Not having a public URL associated with private blobs would be super duper lovely for my application. Thanks,

**Comment by JamieGoodson** [comment]
Hello, is this available? Couldn't see any mention in the docs. Quite surprised as I would've thought this is an essential feature.

A very common scenario is allowing users to upload directly to your storage via a presigned URL. Similarly, if a 3rd party service (that processes audio files for example) needs to access a file from your storage, one would usually provide them with a presigned URL.

**Comment by kgn** [comment]
@vvo is private blobs something that will be added? Sounds like it was something you were looking at back on [Dec 20, 2023](https://github.com/vercel/storage/issues/544#issuecomment-1864262938), but see this ticket is closed now? Is there a separate ticket for supporting `access: 'private'` in Blob?

**Comment by vvo** [comment]
Hey all we're currently focused on getting Vercel Blob out of beta and will start working on private blobs and signed URLs soon after that.

We do have an RFC for private blobs if you want to have a look at and give us feedback on @kgn @theianzhang: https://github.com/vercel/storage/issues/816#issuecomment-2598555512

**Comment by avaer** [comment]
@vvo is this still on the roadmap or forgotten? Last update was coming up on a year ago.

**Comment by vvo** [comment]
Hey there, you can now have private storage for Vercel Blob: https://vercel.com/changelog/private-storage-for-vercel-blob-now-available-in-public-beta

This allows you to implement signed URLs too if you want.
