### ISSUE TITLE
How to get the url by pathname?

### ISSUE THREAD

**Issue by rwecho** [vercel/storage#548]
With the **put** function we can upload a blob and return it with URL . But we must save it in a database? 

If there is no database, how to retrieve the URL when we execute the **del** function?

**Comment by yuriyyakym** [comment]
As far as I understand, the only option besides saving in db is to use [list](https://vercel.com/docs/storage/vercel-blob/using-blob-sdk#list) method.

**Comment by luismeyer** [comment]
👋 @rwecho, if you don't store the URL's in a DB there is two ways to access your blobs. 
1. use the `list` method like @yuriyyakym described. If you already know the pathname you could also send it as a `prefix` in the options object to narrow the response 
2. construct the blob URL's yourself if you know the pathname. The URL schema is: `https://<YOUR_STORE_ID>.public.blob.vercel-storage.com/<YOUR_PATHNAME>`. Your can access the storeId like this: `BLOB_READ_WRITE_TOKEN.split("_")[3]` or in the Vercel Dashboard

**Comment by rwecho** [comment]
Hi @luismeyer , if I put the blob with **addRandomSuffix** , it's conflicts with the method 2.

**Comment by luismeyer** [comment]
true. Than your only option is `list`.

closing this issue now, since it seemed solved
