### ISSUE TITLE
Kysely Migrations fail because VercelPostgresDialect fails to report that VercelPostgres does not support transactions

### ISSUE THREAD

**Issue by jwishnie** [vercel/storage#550]
The Migrator class in Kysely will use transactions if the provided dialect says that the db supports them:
https://github.com/kysely-org/kysely/blob/680eb46d257f58d437ad8f6334255b48d1e9722d/src/migration/migrator.ts#L425

The VercelPostgresDialect class does provides the standard Kysely PostgresAdapter (it fails to override `PostgresDialect.createAdapter`) which reports that transactions _are_ supported:
https://github.com/kysely-org/kysely/blob/680eb46d257f58d437ad8f6334255b48d1e9722d/src/dialect/postgres/postgres-adapter.ts#L10

This causes the Kysely `Migrator` class to attempt to use transactions when running migrations against Vercel/Neon Postgres, which of course fails.

The solution is for the VercelPostgresDialect to report that transactions are _not_ supported by either:
- Subclassing `PostgresAdapter` to create an adapter where `get supportsTransactionalDdl` returns false and returning it
- Returning a proxy to the regular `PostgresAdapter` that intercepts the `get` and returns false

**Comment by jwishnie** [comment]
Submitted a PR to fix this:
https://github.com/vercel/storage/pull/551

**Comment by correttojs** [comment]
thanks for the fix @jwishnie! the PR has been merged 👍
