### ISSUE TITLE
Cannot use @vercel/blob in Edge runtime

### ISSUE THREAD

**Issue by yuriyyakym** [vercel/storage#552]
Whereas everything works fine locally while `vercel dev`, it throws an error when I try to deploy my function using `vercel deploy`:

```
Error: The Edge Function "api/pronunciation" is referencing unsupported modules:
	- @fastify: node:stream
	- undici: stream, net, http, tls, querystring, stream/web, util/types, worker_threads, zlib, perf_hooks, console, url, diagnostics_channel
```

I have found the following comments in this repository:

https://github.com/vercel/storage/blob/8b1ff23e82c992537793469ff4bd194cb8bb34da/packages/blob/src/client.ts#L4-L7

and

https://github.com/vercel/storage/blob/8b1ff23e82c992537793469ff4bd194cb8bb34da/packages/blob/src/undici-browser.js#L1-L8

----

Am I missing any config to make `vercel deploy` use the browser version file?

**Comment by luismeyer** [comment]
hey @yuriyyakym, 
i can't reproduce the issue, running on `next@14.0.3` and `@vercel/blob@0.16.1` (i tried a simple `put` and `list`). Can you describe the steps how to reproduce the issue?

**Comment by yuriyyakym** [comment]
Hey, I do not use `next` for this project. I needed to create a small single-endpoint project. I even had to create a fake `public` directory, otherwise it rejects the deployment.

My config files:

vercel.json
```json
{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "buildCommand": "mkdir -p public && touch public/empty",
  "functions": {
    "api/pronunciation.ts": {
      "memory": 128,
      "maxDuration": 5
    }
  }
}
```

package.json
```json
{
  "dependencies": {
    "@vercel/blob": "^0.16.1",
    "jose": "^5.2.0"
  },
  "devDependencies": {
    "@vercel/edge": "^1.1.1"
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "baseUrl": "./api",
    "target": "es6",
    "lib": ["ESNext", "DOM"],
    "module": "NodeNext",
    "strict": false,
    "noEmit": true
  }
}
```

And then I just imported and used @vercel/blob in my `pronunciation.ts`. If I remove that import and its usage, the function can be properly deployed.

**Comment by luismeyer** [comment]
it seems like, there is currently no way to tell `vercel deploy` to use the browser fetch inside `@vercel/blob`. We are currently planning to remove `undici` from the sdk (https://github.com/vercel/storage/pull/534). This is WIP because we still want to support Node 16, but we are working on a solution. 

For now, I unfortunately only see two options for you:
1. don't run on edge
2. use headless next.js (Because next.js has an additional bundling step, it works here)

**Comment by yuriyyakym** [comment]
Thank you for the detailed response!
