### ISSUE TITLE
Vercel KV Request vs Storage Limit

### ISSUE THREAD

**Issue by patrick-mcdougle** [vercel/storage#555]
In the [limits docs for Vercel KV](https://vercel.com/docs/storage/vercel-kv/limits) it shows that you can store a max record size of 100MB, but you can only have POST requests up to 1MB (max request size). How can you even get a 100MB object into the KV store if you can only post 1MB? Are there ways to append to an existing key in a second request (if so, why doesn't the SDK just do this for me)? Does someone have an example of how to do that? We have an object that is just over 1MB that we'd love to put into KV, but we can't figure out how to get it in there. Help?

**Comment by vvo** [comment]
@patrick-mcdougle Have you tried https://redis.io/commands/append/ or https://redis.io/docs/data-types/hashes/? These would be records that you create and append data to, up to 100MB.

Did you get any errors when trying to put objects bigger than 1MB in one go? Let us know. Sorry for late reply too, thanks

**Comment by patrick-mcdougle** [comment]
@vvo I no longer work for the company who needed this. Perhaps @ahelmholz can weigh in on if this is still important to Thuma.

**Comment by vvo** [comment]
Thank you, please comment if this is still relevant then
