### ISSUE TITLE
insert query are cached 

### ISSUE THREAD

**Issue by smailio** [vercel/storage#556]
When I run an INSERT query through a server action using the sql template string the query is cached, if I run it several time it only runs the first time. 

In this example if I click on the validate button several times, the whole code is run several times but only one row is inserted. 

The table

```
CREATE table DUMB_TABLE (
        id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
        title VARCHAR(255) NOT NULL
)
```

The form

```
      <form action={createDumbTitle}>
        <button type="submit">Validate</button>
      </form>

```

The server action

```
export async function createDumbTitle() {
  await sql<{ title: string }>`
        INSERT INTO DUMB_TABLE (title) VALUES ('dumb_title');
    `;
}

```

**Comment by Darkness-2** [comment]
Getting the same issue when trying out the Next.js learn tutorial. Making the same INSERT or UPDATE query twice results in only one query ever executing.

**Comment by smailio** [comment]
When I delete the cache directory in next it works again so it's definitely that. Maybe I should post on next github ?

**Comment by luismeyer** [comment]
hey @smailio,
this is expected, since all fetch requests on the server are cached by Next.js by default ([docs](https://nextjs.org/docs/app/building-your-application/caching#data-cache))

Ways to fix this could be:
- opt out of the data cache with `unstable_noStore` ([docs](https://nextjs.org/docs/app/api-reference/functions/unstable_noStore))
- call `revalidatePath` or `revalidateTag` to purge the cache manually ([docs](https://nextjs.org/docs/app/api-reference/functions/revalidatePath))

**Comment by vvo** [comment]
@smailio @luismeyer From reading the docs, only GET methods are being cached in Next.js App Router ("Good to know" from https://nextjs.org/docs/app/building-your-application/caching#request-memoization).

And our database client uses POST (https://github.com/neondatabase/serverless/blob/947e5b107f3f3f9c9af1f769d3d7e63a49a43e96/export/httpQuery.ts#L162-L167). So something else is doing caching here, could it be some server action custom behavior?

**Comment by vvo** [comment]
Correction: POST requests are being cached at the moment yep even in server actions. I wrongly linked request memoization (which is a different feature).

The suggestion from @luismeyer should work. And in a future Next.js release POST in server actions won't be cached anymore.
