### ISSUE TITLE
@vercel/kv Inconsistent increment behavior in Server Action

### ISSUE THREAD

**Issue by thomaslenaour** [vercel/storage#557]
I am using the `@vercel/kv` package within a Server Action to increment a counter named `scans`. However, when I check the value using `GET scans` in the Vercel KV CLI on the Vercel Dashboard, the value is not consistently incremented.

Here is my code :
__actions/my-action.ts_
```ts
'use server';

import { kv } from '@vercel/kv';

async function myAction() {
  // ...
  await kv.incr('scans');
}
```
_page.tsx_
```ts
import { kv } from '@vercel/kv';

export const revalidate = 60;

export default async function Home() {
  const scans = await kv.get<string | null>('scans');

  return (
    <p>Scans: {scans || 0}</p>
  );
}
```

### Issue Reproduction
The issue seems to occur intermittently; sometimes, the increment works as expected, and other times it does not. I am unable to determine the underlying cause of this inconsistency.

### Expected Behavior
I expect the `kv.incr('scans')` operation to consistently increment the value of the scans counter. However, the current behavior is inconsistent, and the value is not always updated as expected.

### Additional Context
I have made sure to verify that the issue is not caused by cache revalidation. Even after removing revalidation and forcing the page to be dynamic with `force-dynamic`, the problem persists.

Additionally, how can I work with `@vercel/kv` locally? That is, without needing to use Vercel's remote storage. I tried setting up a Redis on Docker following the issue #281, everything runs perfectly; however, I face the same issue of data persistence and inconsistency: sometimes the counter and/or the value updates correctly, and sometimes not at all. I am unable to explain this behavior.

### Versions
- Node.js v20.9.0
- Next.js 14.0.4
- @vercel/kv 1.0.1

**Comment by luismeyer** [comment]
hey @thomaslenaour,
could you give some more context on from where you are calling the server action?

I just tried this based on the [kv-redis-starter-example](https://github.com/vercel/examples/tree/main/storage/kv-redis-starter) and it works just fine: https://kv-redis-starter-lime-rho.vercel.app. I did not set `revalidate=60` to opt into ISR though.

**Comment by thomaslenaour** [comment]
> hey @thomaslenaour, could you give some more context on from where you are calling the server action?
> 
> I just tried this based on the [kv-redis-starter-example](https://github.com/vercel/examples/tree/main/storage/kv-redis-starter) and it works just fine: https://kv-redis-starter-lime-rho.vercel.app. I did not set `revalidate=60` to opt into ISR though.

Hey @luismeyer, thanks for your response. In fact, here's the implementation I'm working on for a mini project: https://github.com/thomaslenaour/rappelscanner/blob/56402b2571c133f1aa89b708943c12da6ff344e3/app/_actions/product.ts#L52. Indeed, I've already tried playing with the Vercel example and the counter, and it works perfectly.

I feel like I've implemented it correctly, based on the example you mentioned, but I think I might be missing something because I can't get it to work in my project.

The Server Action is called upon form submission, as soon as you click on a "Search" submit button.

- Preview link: https://rappelscanner-git-feat-kv-thomaslenaour.vercel.app
- Repository link on the `feat/kv` branch: https://github.com/thomaslenaour/rappelscanner/tree/feat/kv

**Comment by luismeyer** [comment]
I forked your repo and tried without the revalidation time and a `revalidatePath` call inside the form action. It seems to work now (or are you expecting different results?). Note that when you refresh the page you might see old numbers because the ISR is revalidating the [full router cache](https://nextjs.org/docs/app/building-your-application/caching#full-route-cache) in the background. I guess that could be avoided with `dynamic=force-dynamic` but than you loose the benefit of a fast cached response.

Commit: https://github.com/luismeyer/rappelscanner/pull/1/commits/1c30b1cc92d93a95e5d808c8371f18d017de1cb8
Preview: https://rappelscanner-git-feat-kv-luimey.vercel.app/?vercelToolbarCode=QCiZmInmjrleAx6

**Comment by thomaslenaour** [comment]
Incredible! It seems to be working now. I was convinced that I had already tried it with `revalidatePath`, but it still wasn't working.

Now, it works fine locally (with dockerized Redis) and also works in the Preview environment.

Thank you for your time and for your assistance @luismeyer!

That being said, in an attempt to understand things a bit better: why didn't the change of value occur in my initial code? Apparently, we just added `revalidatePath` and removed the revalidation time. But that shouldn't have an impact on the incrementation of the `scans` value, right?

**Comment by luismeyer** [comment]
Glad I could help :) 

I think beforehand you were running into the [data cache](https://nextjs.org/docs/app/building-your-application/caching#data-cache). `@vercel/kv` is doing `fetch` requests to the upstash API and as stated in the the docs all `fetch` requests are cached by default. `revalidatePath` is purging the data cache and therefor when you call the action again the increment really happens. 

I didn't try it but I think you could even keep the `revalidate=60` in you page segment config.
