### ISSUE TITLE
@vercel/postgres: Extended constant is not working

### ISSUE THREAD

**Issue by 2wheeh** [vercel/storage#558]
Hi!
When I insert or update a text field with the string containing new line characters `\n` with [extended constant](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE) `E''`,
I expect them to be kept but they are not.
- reproduce with:
```sql
CREATE TABLE foo (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    bar TEXT NOT NULL
);
```
```sql
INSERT INTO foo (bar) 
VALUES (E'First Line\nSecond line.');
```
```sql
SELECT
  foo.bar
FROM foo;
```

- expected:
```
First Line
Second line.
```
- current:
```
Fist Line Second line.
```

Am I missing something or is it a bug?

**Comment by luismeyer** [comment]
hey @2wheeh,
where are you trying to display the string? I think the `\n` is present but just not treated correctly.

Here is what I see following your instructions:

Vercel Dashboard:
<img width="957" alt="Screenshot 2024-01-09 at 12 47 18" src="https://github.com/vercel/storage/assets/41523937/054e2d34-497c-471a-9285-ceb85a09de77">

Next.js app:
```ts

async function Test() {
  const foo = await sql<{ bar: string }>`SELECT foo.bar FROM foo`;

  return (
    <div className="grid">
      {foo.rows.map((row, i) => (
        <span className="whitespace-pre-line" key={`${row} ${i}`}>
          {row.bar}
        </span>
      ))}
    </div>
  );
}
```

<img width="137" alt="Screenshot 2024-01-09 at 12 47 56" src="https://github.com/vercel/storage/assets/41523937/6f1b46f9-33ba-4c49-b6d8-b3898a7ab4ea">

The trick here is `whitespace-pre-wrap` to correctly interpret the `\n` (https://stackoverflow.com/questions/39325414/line-break-in-html-with-n)

i hope this helps

**Comment by 2wheeh** [comment]
@luismeyer Thanks it helps me a lot. I was checking it on dashboard.
Can I give you one more question though? 

I'm struggling with making queries with `E`  and tag functions in template literal:
Do you have any guess for this ??

**Edit**:
working:
```ts
await sql`
    UPDATE foo
    SET bar = E'hello'
    WHERE id = ${id}
`;
```

not working:
```ts
const baz = 'hello';
await sql`
    UPDATE foo
    SET bar = E'${baz}' 
    WHERE id = ${id}
`;
// ERROR: could not determine data type of parameter $1
```

```ts
const baz = 'hello';
await sql`
    UPDATE foo
    SET bar = E${baz}
    WHERE id = ${id}
`;
// ERROR: column "e$1" does not exist
```

**Comment by 2wheeh** [comment]
>  I think the \n is present but just not treated correctly.

FYI, I just checked it is reproduced in neon dashboard too:
<img width="208" alt="image" src="https://github.com/vercel/storage/assets/40269597/b482dd0f-8727-438b-a8fa-0704f694cba7">

**Comment by luismeyer** [comment]
That is not possible since `${baz}` is converted into `$1` and the value is passed as a parameter.

That said I think you don't need the `E` here because parameters are automatically escaped

**Comment by 2wheeh** [comment]
Yes It works. Thank you so much for kindly answering. It turned out the bug in my code was not around here. I hope the dashboard to show correctly though. Thanks again.

It was `<input>` in the `<form>`. I am using server action to fetch with form and input element. The input element strips off the line breaks of its string value. So replacing it with textarea fixed my bug.
