### ISSUE TITLE
Vercel KV not reachable

### ISSUE THREAD

**Issue by paulbuskovskij** [vercel/storage#572]
What am I doing wrong, can anyone help me?

<img width="1230" alt="vercel_kv_error" src="https://github.com/vercel/storage/assets/66474705/bfc6adce-9a79-472d-a428-cc2e98026358">

**Comment by correttojs** [comment]
could be related to https://www.vercel-status.com/incidents/cnywbl7zfyq5? Does it work now?

**Comment by correttojs** [comment]
closing as the incident has been solved
