### ISSUE TITLE
X-Frame-Options set to DENY prevents embedding PDF blob in object, embed or iframe

### ISSUE THREAD

**Issue by jferrel7** [vercel/storage#591]
@PeytonCleveland @jferrel7 the latest release of `@vercel/blob` creates pdf files with an `inline` content-disposition, allowing you to display them as you wish 👍

_Originally posted by @vvo in https://github.com/vercel/storage/issues/509#issuecomment-1893336585_

I'm just now getting a chance to test this fix, and I see the new Content-Disposition header value `inline`, but the X-Frame-Options header value is DENY which prevents the pdf file from being viewed in an object, embed or iframe HTML tag. It seems the X-Frame-Options header should be removed in order for embedding PDFs to work.

**Comment by lukahartwig** [comment]
Hey @jferrel7, thanks for flagging this. I'll double check with our security team.

**Comment by jferrel7** [comment]
Thanks @lukahartwig

**Comment by lukahartwig** [comment]
The header is now removed and embedding PDFs should work now. If you encounter any problems feel free to reopen this issue.
