### ISSUE TITLE
[Blob] No response from the server

### ISSUE THREAD

**Issue by nr1brolyfan** [vercel/storage#595]
I'm trying to upload files using Vercel Blob
```ts
// SvelteKit action
let imageUrl: string | null = null;
const formData = await request.formData();
const image = formData.get('image');

if (image instanceof File) {
    try {
        const { url } = await put(image.name, image
            access: 'public',
            token: env.BLOB_READ_WRITE_TOKEN
        });
        imageUrl = url;
    } catch (error) {
        console.error('vercel blob error', error);
    }
}
```
But the `put()` function doesn't immediately resolve with a success response or an error. It leaves me hanging for several minutes then throws an error:
```
TypeError: fetch failed
    at fetch (...\undici@5.28.2\node_modules\undici\index.js:112:15)
    at async .../@vercel+blob@0.22.0/node_modules/@vercel/blob/dist/chunk-BK7PAFRM.js:160:19
  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
      at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
```

Caveats:
```
• Sometimes this issue just does not occur - I've tried many things (different file sizes, formats, browsers, incognito mode, restarting the dev server, etc.) and still can't find the pattern. 
  To me it seems completely (!) random and it works normally one in a 5-10 times (maybe)
• This is not a SvelteKit issue, same thing happening with Next.js (app router)
• I tried different WiFi, disabling the firewall and antivirus protection - no effect
```

I have the same issue with Uploadthing (I think Blob and UT both use S3) and this is what the server response shows when turned into text (await response.text()):
```html
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>...</RequestId><HostId>...</HostId></Error>
```

**Comment by vvo** [comment]
Hey there @szymondlugolecki, since you said:

> I have the same issue with Uploadthing 

And, knowing that both Uploadthing and Vercel Blob are built in very different ways (we're not using AWS S3, they are). The fact that you're having connection timeouts between the two does seems a bit strange.

What I do in these moments of doubt is to start with what you know always works. Create a simple Node.js script and try to upload a simple string like "Hello world" to a blob. See if this works 100% of the time (it should). Then gradually add more complexity until you uncover what fails.

You can also try to change your code to:

```
        const { url } = await put('fake name', 'fake data'
            access: 'public',
            token: env.BLOB_READ_WRITE_TOKEN
        });
```

and see if this works all the time.

**Comment by vvo** [comment]
For completeness, you could also try to:
- use the alternative way of receiving data, just to see if this works 100% of the time versus server actions https://kit.svelte.dev/docs/form-actions#alternatives
- use multipart: true in the put command

**Comment by vvo** [comment]
Finally, it does seems like other SvelteKit users have experienced random issues with file uploads here: https://github.com/sveltejs/kit/issues/5490

**Comment by nr1brolyfan** [comment]
Interesting. When debugging I used to upload the same file 20 times in a row and the result was never consistent, which suggested to me it's not a SvelteKit issue or file issue as they stayed the same with every upload.
This made me blame networking/AWS, but I followed your instructions and first found that it works every time when reading the file with `fs`, which probably means something goes wrong when sending the image to my backend.

Anyway, here's what worked. Just one line of code that first turns the file to a Buffer before passing it to the `put()` function
```ts
// Old code
const { url } = await put(file.name, file, {
    access: 'public',
    token: env.BLOB_READ_WRITE_TOKEN
});

// New code
const fileBuffer = Buffer.from(await file.arrayBuffer());
const { url } = await put(file.name, fileBuffer, {
    access: 'public',
    token: env.BLOB_READ_WRITE_TOKEN
});
```
It's still interesting as I seem to be the only person having this issue and your Blob with SvelteKit example doesn't work for me (at least not consistently).
![image](https://github.com/vercel/storage/assets/88940768/aadee7cb-6bf7-41b3-911f-049768165005)

**Comment by ross-weir** [comment]
I had the same issue described here and the same solution appears to have fixed it - converting the file to a buffer

Using NextJS 14, using server actions

**Comment by vvo** [comment]
Nice, Buffer it is then 👍

**Comment by Newstein123** [comment]
I have the same issue and buffer solved
