### ISSUE TITLE
Vercel Blob onBeforeGenerateToken clientPayload Type issue?

### ISSUE THREAD

**Issue by alex-moore-codes** [vercel/storage#597]
Let me preface with I am relatively new to Typescript (and web development in general), so please help me understand if I am doing something wrong.

That being said, it looks like the type for the optional `clientPayload` param of `onBeforeGenerateToken`, which is currently set to `string | null` should be updated to `string | undefined`. 

The docs say that you should pass a string to this optional parameter. When I take the Vercel code as a starting point (below), and then uncomment the line that reads `clientPayload?: string`, I get a Typescript error: `Type 'null' is not assignable to type 'string | undefined'.ts(2322)`.

I was able to fix the Typescript error by updating the type for `clientPayload` from `string | null` to `string | undefined`.

To my knowledge, this should work fine because, at least in my case (I understand other people may have other instances where this wouldn't make sense?), I would never pass a `null` `clientPayload`... I either have a payload to pass or I don't, in which case it would be `undefined`.

Perhaps my "solution" creates additional problems. If so, please share! If the types were defined this way for a reason, and I am just doing something wrong... please share! 😆

```
onBeforeGenerateToken: async (
        pathname: string,
        clientPayload?: string, <--- when I remove the comment from this line, Typescript gets mad, until I change the type to string | undefined.
      ) => {
        // Generate a client token for the browser to upload the file
        // ⚠️ Authenticate and authorize users before generating the token.
        // Otherwise, you're allowing anonymous uploads.
 
        // ⚠️ When using the clientPayload feature, make sure to valide it
        // otherwise this could introduce security issues for your app
        // like allowing users to modify other users' posts
 
        return {
          allowedContentTypes: ['image/jpeg', 'image/png', 'image/gif'], // optional, default to all content types
          // maximumSizeInBytes: number, optional, the maximum is 5TB
          // validUntil: number, optional, timestamp in ms, by default now + 30s (30,000)
          // addRandomSuffix: boolean, optional, allows to disable or enable random suffixes (defaults to `true`)
          // cacheControlMaxAge: number, optional, a duration in seconds to configure the edge and browser caches.
          tokenPayload: JSON.stringify({
            // optional, sent to your server on upload completion
            // you could pass a user id from auth, or a value from clientPayload
          }),
        };
      },
```

**Comment by luismeyer** [comment]
hey @alex-moore-codes,

`null` is actually the fallback value in our SDK if you don't pass a value on the client side. So the typings are correct.

That said I think this is a valid bug in the docs. I think the best solution is to delete the type annotation completely like this:
```ts
onBeforeGenerateToken: async (pathname, clientPayload) => {}
```

This is possible because the SDK already defines the function type that has to be passed to `onBeforeGenerateToken`. So typescript can just infer the types without you having to define them manually.

I'll update the docs. Thank you for flagging this

**Comment by alex-moore-codes** [comment]
Hey @luismeyer,

Thanks for the quick reply! Deleting the type annotation doesn't seem to do anything either (I had already tried that and forgot to mention it in my original post). This just creates a different Typescript error: `Type 'null' is not assignable to type 'string'.ts(2322)`

EDIT: Unless you're suggesting to remove the String annotation as well. If so, then yes, it works.

**Comment by luismeyer** [comment]
no, I meant deleting the types completely, also the `string`. This will always infer the type the SDK provides.
