### ISSUE TITLE
x-axis visibility issue for extended columns in postgres table 

### ISSUE THREAD

**Issue by ashishsah1000** [vercel/storage#615]
To replicate:
Navigate to any PostgreSQL database, create a table with multiple columns, and access the table either through a dropdown or by executing a query. If a column extends beyond the visible space occupied by the table, it becomes inaccessible on the x-axis.

This is a table in which I cannot scroll to the right. Maybe something related to `overflow`.

<img width="1499" alt="image" src="https://github.com/vercel/storage/assets/24749090/482c635e-4564-4e24-8224-86556fae8017">

**Comment by vvo** [comment]
@ashishsah1000 While not the best experience, you can scroll this table using horizontal scroll either with:
- touchpad gestures
- SHIFT + mouse wheel
- select column names to the right to force scrolling

Here's a demo video:

https://github.com/vercel/storage/assets/123822/3ff19bc5-c224-417f-90f5-969eba22cf2b

Good luck!
