### ISSUE TITLE
pg.types.setTypeParser() not working with @vercel/postgres-kysely package

### ISSUE THREAD

**Issue by Trimud** [vercel/storage#625]
Hello,

I'm using Vercel Postgres and Kysely with `@vercel/postgres-kysely` npm package.
I have a `cout()` function in my query that returns bigint as stated [here](https://www.postgresql.org/docs/16/functions-aggregate.html#:~:text=count%20(%20*,of%20input%20rows.).

I want to return number, instead. of string for the result of the count function as stated here: https://kysely.dev/docs/recipes/data-types

```
const int8TypeId = 20
// Map int8 to number.
pg.types.setTypeParser(int8TypeId, (val) => {
  return parseInt(val, 10)
})
```

This works if I connect to Kysely directly like this:
```
export const db = new Kysely<Database>({
  dialect: new PostgresDialect({
    pool: new pg.Pool({
      connectionString: process.env.POSTGRES_URL,
      max: 10,
      ssl: true,
    }),
  }),
});
```
But not if I use createKysely from `@vercel/postgres-kysely` package. Even if I use the same config.
```
import { createKysely } from "@vercel/postgres-kysely";
...
export const db = createKysely<Database>(
  {},
  {
    dialect: new PostgresDialect({
      pool: new pg.Pool({
        connectionString: process.env.POSTGRES_URL,
        max: 10,
        ssl: true,
      }),
    }),
  }
);
```
Any hint would be greatly appreciated, thanks in advance!

**Comment by vvo** [comment]
Hi @Trimud, you have two options here:

1. Keep using `@vercel/postgres-kysely`

You can keep using this module, and try to achieve what you want. To do so will probably require:
> `npm add @neondatabase/serverless@0.7.2` (the version we're currently using)

And then:

```ts
import { createKysely } from '@vercel/postgres-kysely';
import { types } from '@neondatabase/serverless';
import { parse } from 'json-custom-numbers';

function parseJSONWithBigInts(str) {
  return parse(str, undefined, function (k, str) {
    const n = +str;
    const safe = n >= Number.MIN_SAFE_INTEGER && n <= Number.MAX_SAFE_INTEGER;
    return safe || /[.eE]/.test(str) ? n : BigInt(str);
  });
}
types.setTypeParser(types.builtins.JSON, parseJSONWithBigInts);
types.setTypeParser(types.builtins.JSONB, parseJSONWithBigInts);
```

As seen here: https://neon.tech/blog/parsing-json-from-postgres-in-js#presenting-json-custom-numbers

2. Do not use `@vercel/postgres-kysely`, use kysely + https://github.com/neondatabase/serverless/

In this solution, you avoid using our "smart" wrapper and use directly the neon (our provider behind vercel/postgres) driver and kysely directly. You'll find more information on how to do so here: https://github.com/seveibar/kysely-neon.

Good luck!
