### ISSUE TITLE
ReferenceError: TextDecoder is not defined While using blob storage in test cases

### ISSUE THREAD

**Issue by sarabs3** [vercel/storage#628]
I am using blob storage for the first time and after implementing it in the code, while running the tests I am getting this error.
**ReferenceError: TextDecoder is not defined**

This is my code 
```
import { upload } from '@vercel/blob/client';

export const uploadMediaFile = async (file: File, userName: string) => {
  try {
    const newBlob = await upload(`${userName}/${file.name}`, file, {
      access: 'public',
      handleUploadUrl: upload,
    });
    return newBlob.url;
  } catch (error) {
    console.error(error);
    throw new Error('error uploading media files');
  }
};
```

Error in jest

<img width="694" alt="Screenshot 2024-03-07 at 9 45 25 PM" src="https://github.com/vercel/storage/assets/3119576/0dc505a4-ce58-41e6-b2d1-4d257e379dfa">

**Comment by dferber90** [comment]
Which node version are you using? Older node versions don't expose TextDecoder as a global.  Try upgrading node if it's below version 12. Otherwise it might be related to how your testing environment is configured.

**Comment by dferber90** [comment]
If you're using Jest check out this solution to define TextDecoder and TextEncoder https://github.com/mswjs/msw/issues/1796#issuecomment-1782351156

**Comment by vvo** [comment]
Hey there, yes this is a Jest issue. We actually fixed it in our code too: https://github.com/vercel/storage/blob/main/packages/blob/jest/setup.js

Good luck!
