### ISSUE TITLE
I have issue while integrating vercel blobs using server actions.

### ISSUE THREAD

**Issue by best-luck** [vercel/storage#629]
Hello, there!

Here is my approach to save file.

**- frontend**

<form action={props.saveBanner}>
        <div className="mt-5">
          <label className="font-bold mb-3" htmlFor="heading">Heading</label>
          <input 
            id="heading"
            name="heading"
            type="text"
            autoComplete="heading"
            placeholder="Heading"
            onChange={updateBanner}
            required
            className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 px-3"
          />
        </div>
        
        <div className="mt-3">
          <label className="font-bold mb-3">Subheading</label>
          <input 
            id="subheading"
            name="subheading"
            type="text"
            autoComplete="subheading"
            placeholder="subheading"
            required
            onChange={updateBanner}
            className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 px-3"
          />
        </div>

        <div className="mt-3">
          <label className="font-bold mb-3">Image</label>
          <input 
            id="image"
            name="image"
            type="file"
            autoComplete="image"
            placeholder="Image"
            required
            onChange={imageCallback}
            className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 px-3"
          />
        </div>

        <div className="mt-3">
          <label className="font-bold mb-3">Link</label>
          <input 
            id="link"
            name="link"
            type="text"
            autoComplete="link"
            placeholder="Link"
            required
            onChange={updateBanner}
            className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 px-3"
          />
        </div>

        <div className="mt-3">
          <label className="font-bold mb-3">CTA</label>
          <input 
            id="cta"
            name="cta"
            type="text"
            autoComplete="cta"
            placeholder="CTA"
            required
            onChange={updateBanner}
            className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 px-3"
          />
        </div>

        <div className="flex justify-end mt-5">
          <Button
            onClick={() => router.back()}
            className="bg-rose-600 text-white px-5 me-3"
            type="button"
            >
            Back
          </Button>
          <Button
            onClick={() => {}}
            className="bg-cyan-400 text-white px-5"
            type="submit"
            >
            Add
          </Button>
        </div>
      </form>

**- backend**

const saveBanner = async (formData: FormData) => {
    'use server';

    const imageFile = formData.get('image') as File;
    console.log('here', imageFile.name, imageFile);
    const readStream = await imageFile.stream();
    const blob = await put(imageFile.name, readStream, {
      access: 'public',
    });
    console.log('here1')
    revalidatePath('/');
    return blob;
  }

After it, i got this image url but I can't visit the url
https://tq4op7s2k335xqoq.public.blob.vercel-storage.com/wallpaperflare.com_wallpaper%20(23)-j4BVhNk3RoP2tCjv3zV0E5qVjIMjEu.jpg

Thanks in advance.

**Comment by vvo** [comment]
Hey @build-green-earth, it seems this Vercel Blob store has been deleted already, did you delete it?

**Comment by best-luck** [comment]
Yes, I already deleted but the url didn't work at that time.
It shows 404 not found for the url

**Comment by vvo** [comment]
Now that I look again, I see you have literal `%` in the pathname, this could have been the issue. I'll close for now, if you want to try again let me know. We recommend you normalize pathnames to avoid URL conflicting characters like `%` or `#`. We'll probably do this automatically in future versions of Vercel Blob.

**Comment by best-luck** [comment]
Okay, thanks for your reply.
But I couldn't upload images to blob in the vercel admin dashboard.
