### ISSUE TITLE
hobby bandwidth limit

### ISSUE THREAD

**Issue by Codigo-Fuentes** [vercel/storage#631]
I, and others from i've seen, used up vercel blob storage bandwidth limit within 1 day while testing an app doing almost nothing with one person.

Suggestion: **Remove vercel blob storage from hobby plans**.

I have now wasted all the time i used implementing it and have to rip it out. It would have been better to not have the option or have been warned that it was useless on the hobby plan.

**Comment by vvo** [comment]
@Codigo-Fuentes I am sorry you lost all this time on Vercel Blob. You are correct to suggest we could remove it from the hobby plan completely. We'll think about that. Thanks for the feedback again, really appreciate it.
