### ISSUE TITLE
Can't delete blob file.

### ISSUE THREAD

**Issue by tkrzhkv** [vercel/storage#634]
Hello, I got issue with deleting of blob file from vercel blob storage. I got 500.  Anyone can help ? Is it my mistake ? Thanks in advance :) 

![image](https://github.com/vercel/storage/assets/104071834/6f3d506e-446d-4834-b2bd-253e87610e99)

![image](https://github.com/vercel/storage/assets/104071834/677706ab-ea6b-4d9b-97db-bd40b2280e51)

![image](https://github.com/vercel/storage/assets/104071834/cac9c6d3-1ad4-4317-8812-23eb3d9c0f22)

![image](https://github.com/vercel/storage/assets/104071834/0f23d638-7edb-4d86-9bec-530d6eee2980)

![image](https://github.com/vercel/storage/assets/104071834/da463038-105c-41e2-8377-94905a3c5945)

**Comment by tkrzhkv** [comment]
If anyone will meet this issue, then just change you Detele request to this and it will work. 

![image](https://github.com/vercel/storage/assets/104071834/9000aa54-11dc-4885-8192-81341c28642a)

**Comment by luismeyer** [comment]
closing this, since it seems to be solved. Feel free to reopen
