### ISSUE TITLE
Broken Uploaded Images on Blob via Express Js

### ISSUE THREAD

**Issue by fres-sudo** [vercel/storage#637]
Hi everyone, i got a express js server (node version: v21.7.1) hosted on vercel, when i try to upload photo on blob via express server, everything works just fine apart from the fact that the images uploaded are broken and only of 15B.

<img width="364" alt="Screenshot 2024-03-22 alle 10 52 08" src="https://github.com/vercel/storage/assets/65305708/88c9a85c-c4f8-417d-8978-616935a7fa89">
<img width="305" alt="Screenshot 2024-03-22 alle 10 52 21" src="https://github.com/vercel/storage/assets/65305708/94ebe2a2-a36e-4240-9b9d-99b791ad302a">
<img width="159" alt="Screenshot 2024-03-22 alle 10 52 35" src="https://github.com/vercel/storage/assets/65305708/930d569e-33e1-48cb-91f0-ce52abafcbff">

The mac alert just says that it is impossible to open the file, that the file might be corrupted or unsupported.

The [Preview Link](https://jjsfgfmzoftauon7.public.blob.vercel-storage.com/user-65e31000c48a3a97e1a5147a-1711028389561-JXNGA91yIFELfmXN6Ho7bvt2y38A5T.jpeg) and [Download Link](https://jjsfgfmzoftauon7.public.blob.vercel-storage.com/user-65e31000c48a3a97e1a5147a-1711028389561-JXNGA91yIFELfmXN6Ho7bvt2y38A5T.jpeg?download=1)

I tried two ways to solve this issue but in both ways the only thing that i got back is 200 status code but with a 15B images, even if the image has been uploaded correctly (notice also that i'm testing everything on postman).

1. PUT call
Route: 
```javascript
import multer from "multer";
const upload = multer();

router.route('/:id').put(upload.single('photo'), userController.updateUser)
```
Controller:
```javascript

export const updateUser = catchAsync(async (req, res, next) => {
  try{  
    if(req.file){
      const filename = `user-${req.user.id}-${Date.now()}.jpeg`;
      console.log(req.file);

      const result = await put(filename, req.file, 
        { access: 'public', 
        token : process.env.BLOB_READ_WRITE_TOKEN,
        addRandomSuffix: false,
      },); 
     
      console.log({result});
    }

    //db stuff...

} catch (err) {
  res.status(400).json({
    status: 'error',
    message: err.message,
  });
}
});

```
Console result:
```bash
{
  fieldname: 'photo',
  originalname: '_ (20).jpeg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  buffer: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 01 00 48 00 48 00 00 ff db 00 43 00 06 04 05 06 05 04 06 06 05 06 07 07 06 08 0a 10 0a 0a 09 09 0a 14 0e 0f 0c ... 34195 more bytes>,
  size: 34245
}
{
  result: {
    url: 'https://jjsfgfmzoftauon7.public.blob.vercel-storage.com/user-65e31000c48a3a97e1a5147a-1711101529160.jpeg',
    downloadUrl: 'https://jjsfgfmzoftauon7.public.blob.vercel-storage.com/user-65e31000c48a3a97e1a5147a-1711101529160.jpeg?download=1',
    pathname: 'user-65e31000c48a3a97e1a5147a-1711101529160.jpeg',
    contentType: 'image/jpeg',
    contentDisposition: 'inline; filename="user-65e31000c48a3a97e1a5147a-1711101529160.jpeg"'
  }
}

```

2. POST call:

Route:
```javascript
router.post('/uploadPhoto', upload.single('photo'), userController.uploadFile);
```
Controller:
```javascript
 export const uploadFile = async (req, res) => {
  try {
    const file = req.file;
    console.log({file});
    const blob = await put(file.originalname, file, { access: 'public' , token : process.env.BLOB_READ_WRITE_TOKEN,  });
    console.log({blob});
    res.json({blob});
  } catch (err) {
    res.status(500).json({ error: 'An error occurred while uploading the file.' });
  }
}
```
Console result:
```bash
{
  file: {
    fieldname: 'photo',
    originalname: '_ (13).jpeg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    buffer: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 01 00 48 00 48 00 00 ff db 00 43 00 06 04 05 06 05 04 06 06 05 06 07 07 06 08 0a 10 0a 0a 09 09 0a 14 0e 0f 0c ... 21792 more bytes>,
    size: 21842
  }
}
{
  blob: {
    url: 'https://jjsfgfmzoftauon7.public.blob.vercel-storage.com/_%20(13)-uUVosoz5TYonKwqvrrso3dWtPjX8ON.jpeg',
    downloadUrl: 'https://jjsfgfmzoftauon7.public.blob.vercel-storage.com/_%20(13)-uUVosoz5TYonKwqvrrso3dWtPjX8ON.jpeg?download=1',
    pathname: '_ (13).jpeg',
    contentType: 'image/jpeg',
    contentDisposition: 'inline; filename="_%20(13).jpeg"'
  }
}
```

⚠️Please notice that both ways are being tested on local host and on vercel and in both cases i got the same issue.
Notice also that i'm sending data via form-data option in postman
<img width="386" alt="Screenshot 2024-03-22 alle 11 04 34" src="https://github.com/vercel/storage/assets/65305708/4fb19837-9a49-4601-b0c6-20f97b1ce965">

P.S. I don't know why but within the thousand of tests that i made in these days, one time i got it right:
<img width="624" alt="Screenshot 2024-03-22 alle 11 02 42" src="https://github.com/vercel/storage/assets/65305708/27c80c17-3ff3-4c64-91e3-581d1b99b2a2">
But i honestly cant remember how i ended up doin that.

I you need other information, please let me know. Thanks <3.

**Comment by vvo** [comment]
@fres-sudo so sorry you're getting through all this trouble here.

Here's how to fix your issue:

Controller:
```ts
 export const uploadFile = async (req, res) => {
  try {
    const file = req.file;
    console.log({file});
    // see next line: file.buffer instead of file
    const blob = await put(file.originalname, file.buffer, { access: 'public' , token : process.env.BLOB_READ_WRITE_TOKEN,  });
    console.log({blob});
    res.json({blob});
  } catch (err) {
    res.status(500).json({ error: 'An error occurred while uploading the file.' });
  }
}
```

What's happening: because you're trying to upload the whole `file` object, it gets sent as is (like a JSON object) and the actual buffer object gets ignored. We'll work on better error messages so you can solve this faster next time.

Change your filename to txt on your desktop and you'll see this: 
![CleanShot 2024-03-22 at 13 57 57@2x](https://github.com/vercel/storage/assets/123822/c5cf494d-ade8-46e6-8f2d-1645a439e09f)

Godd luck!

**Comment by fres-sudo** [comment]
@vvo Can't describe how grateful i am, big thanks also for the hint of the file extension, i completely ignore it.

God bless you, and all your team!
