### ISSUE TITLE
@vercel/blob - is it possible to cancel uploading a file?

### ISSUE THREAD

**Issue by pie6k** [vercel/storage#639]
Currently - `put` method seems to be returning a promise when the upload is done.

In my case - it is possible that the user will cancel the operation in the middle. Is it possible to cancel file upload then, so there are no unwanted artifacts and uploads left and there is no wasted network traffic?

**Comment by vvo** [comment]
@pie6k No, not yet, but we wanted to allow it soon, yes. We would have something like this:

```ts
controller = new AbortController();
await put(filename, content, { access: "public", abortSignal: controller.signal });

setTimeout(() => {
  controller.abort();
}, 300);
```

What do you think?
https://developer.mozilla.org/en-US/docs/Web/API/AbortController

**Comment by pie6k** [comment]
Looks great and I like the API

**Comment by ghost** [comment]
Would you kindly showcase how this can now be used by the client to abort a server upload?
I am not sure if I am missing something here but as far as I understand, the `put` method is only usable with server uploads  so I don't  see much need for adding an abort controller to it. But this would likely be a useful feature for the `upload` method in `@vercel/blob/client`.

**Comment by luismeyer** [comment]
@trentcharlie we will provide the abortSignal option to all existing operations. Request canceling with client uploads would look something like this:

```ts
const result = await upload(name, file, {
  access: "public",
  contentType: file.type,
  handleUploadUrl: "handler/api/",
  abortSignal: abortController.signal
});

abortController.abort()
```
