### ISSUE TITLE
Upload/Download Progress on Vercel Blob 

### ISSUE THREAD

**Issue by fahidsarker** [vercel/storage#642]
I am currently using vercel blob to store large files and not showing the progress results in a very bad user experience. Can we have this feature soon?

**Comment by luismeyer** [comment]
hey @fahidsarker,
this is on our roadmap and we are planning to implement this. 

Are you using the multipart upload or the plain put method?

**Comment by xavimb** [comment]
We're having the same issue. We're using the multipart upload, typically with large files.

**Comment by patrickdevivo** [comment]
We're also using Vercel Blob and taking the client-side upload approach (in our Next.js app) and would love to show an upload progress bar, especially for larger file uploads.

**Comment by jonathantcrawford** [comment]
If you are using @vercel/blob/client package in a NetxtJs app router, I think I have a temp solution.

util.ts
```
"use server"
import { upload, generateClientTokenFromReadWriteToken } from "@vercel/blob/client";

import { ORIGIN } from "@/lib/constants";




export const secureGenerateClientTokenFromReadWriteToken = async ({
  userId,
  pathname,
}: {
  userId: string;
  pathname: string;
}) => {

  return generateClientTokenFromReadWriteToken({
    token: process.env.BLOB_READ_WRITE_TOKEN,
    pathname: pathname,
    onUploadCompleted: {
      callbackUrl: `${ORIGIN}/api/user/upload`,
      tokenPayload: JSON.stringify({
        userId,
      }),
    }
  })
}
```

Then from inside your client component.
```
        const pathname = `${user.id}/${file.name}`;
        const token = await secureGenerateClientTokenFromReadWriteToken({
          userId: user.id,
          pathname,
        });
        await axios.put(
          `https://blob.vercel-storage.com/${pathname}`,
          file,
          {
            headers: {
              "Authorization": `Bearer ${token}`,
            },
            onUploadProgress: (progressEvent) => {
              console.log(progressEvent);
            }
          }
        )
       ```

**Comment by Vitalii-Hurieiev** [comment]
This progress functionality is important for our project as well. Displaying the download progress is essential for users, as varying file sizes or slow internet connections can make the process appear frozen.

**Comment by alan-funded** [comment]
Important for us also, we have mobile users thinking the upload did not work, and uploading a second time.

**Comment by neoromantic** [comment]
Any idea on whether it'll be implemented anytime soon? 

I need to understand should I move to S3 uploads instead of Vercel Blob or not.

**Comment by vvo** [comment]
Hey there, we just published a preview version of `@vercel/blob` which includes a way to track the progress of uploads.

If you want to try it, please upgrade to `@vercel/blob@0.26.0-a0c75211-20241025223154` in your package.json. Then use it this way:

```ts
// also works with upload()
const blob = await put('file.pdf', file, {
  onUploadProgress(event) {
    console.log(event.loaded, event.total, event.percentage);
  }
});
```

If you're using Next.js and getting errors about undici, please upgrade to at least `next@14.2.0` or force undici to be at version 5 in your package.json using pnpm overrides for example: https://pnpm.io/package_json#pnpmoverrides.

cc @fahidsarker @xavimb @patrickdevivo @jonathantcrawford @alan-funded @neoromantic @Vitalii-Hurieiev

**Comment by alan-funded** [comment]
Thanks, this will allow our customers to know their upload is actually
happening :)

**Comment by vvo** [comment]
@alan-funded I am curious: are the uploads from your customers big enough that upload progress is needed? I think it's always a valuable info, just curious here

**Comment by alan-funded** [comment]
Tens of megabytes, but often from cell phone, and on the go. AlanOn Oct 25, 2024, at 4:26 PM, Vincent Voyer ***@***.***> wrote:﻿
@alan-funded I am curious: are the uploads from your customers big enough that upload progress is needed? I think it's always a valuable info, just curious here

**Comment by fahidsarker** [comment]
Huge thanks to the team for the update. Will close the issue as it has been resolved.

**Comment by arazardev** [comment]
@vvo  Hey, im just using Vercel Blob for the first time and this works with no problem! Thanks for this feature. In argentinian i'll say: ¡qué grande!

**Comment by vvo** [comment]
Nice @arazardev! Will publish a stable version this week then

**Comment by vvo** [comment]
This feature is now released in `@vercel/blob@26.0.0`, it's compatible with Node.js, browsers, client or server uploads, and most recent Next.js versions too.

**Comment by vvo** [comment]
For everyone here, since this was a well followed ticket, I wanted to raise your awareness on an upcoming change we'd like to do on Vercel Blob SDK: no more random suffixes by default. Please join the conversation here:
https://x.com/vvoyer/status/1854816275173634175

**Comment by livebeauty** [comment]
thank u
