### ISSUE TITLE
@vercel/postgres: How to connect to a localhost database for development work?

### ISSUE THREAD

**Issue by pkMinhas** [vercel/storage#658]
I am trying to connect to a localhost database for the purpose of development and testing. However, I keep getting ECONNREFUSED on 443. 
Are self-hosted databases supported when using vercel/postgres?

**Comment by luismeyer** [comment]
`@vercel/postgres` is build on top of `@neondatabase/serverless`. I think you need to run a local websocket proxy in front of your database so that the sdk can connect to it: https://github.com/neondatabase/serverless?tab=readme-ov-file#bring-your-own-postgres-database

**Comment by pkMinhas** [comment]
Thank you, I'll investigate that.

**Comment by artola** [comment]
@pkMinhas did you manage to run in your self-hosted db? Any hint will be appreciated.

**Comment by pkMinhas** [comment]
> @pkMinhas did you manage to run in your self-hosted db? Any hint will be appreciated.

I was unable to get it running on my system

**Comment by vvo** [comment]
Hey there, here's how to have a local Postgres database and connect to it with `@vercel/postgres`: https://github.com/vercel/storage/issues/123#issuecomment-2326100123
