### ISSUE TITLE
hgetall 获取数据类型异常

### ISSUE THREAD

**Issue by Hyk260** [vercel/storage#669]
![2`8`NF8NQ6Z`1K_JIZ7DL3H](https://github.com/vercel/storage/assets/85072491/66d1575f-dbcd-4bf1-9ac8-6d4b18d2f051)

**Comment by luismeyer** [comment]
`hset` is expecting field value pairs and not an object ([redis docs](https://redis.io/docs/latest/commands/hset/))
This causes `HSET userSession { userId: 123, email: ...` to become `"{": "userId:", "123,": "email:" ...`

The correct way you want to use hset is probably:
`hset 'admin' 'userId' 123 'email' 'ex@example.com'`

Also if you keep seeing weirdly scrambled results it might help flushing the DB. Keep in mind that this deletes you data though.
