### ISSUE TITLE
Can I use KV with a local Redis?

### ISSUE THREAD

**Issue by louis030195** [vercel/storage#673]
Hi, always love the clean API of vercel, been using KV with upstash/vercel redis for a while, wondering if it's possible to use a local redis? Assuming it's not well documented because not aligned with Vercel business model :)

Mostly for internet gapped use case

**Comment by luismeyer** [comment]
hey, 
`@vercel/kv` is build in top of `@upstash/redis` and that's a http client for the upstash rest API. So you would need to run the upstash API locally in order to have a setup that runs offline. AFAIK thats not possible, sorry

**Comment by luismeyer** [comment]
I think my other answer was wrong.
you can have a look here: https://upstash.com/docs/oss/sdks/ts/redis/developing or in this issue: https://github.com/vercel/storage/issues/281
