### ISSUE TITLE
Vercel blob: url vs downloadURL?

### ISSUE THREAD

**Issue by Vimblin** [vercel/storage#689]
I have a functionality that a user can upload an avatar clientside on my website. I store the uploaded avatar in my vercel blob storage and it returns me a blob object with following included properties: url, downloadUrl. What is the difference between theese urls and when I should use which? Which url I should store in my sql database to display the avatar later?

**Comment by vvo** [comment]
@Swoopify To display the avatar on a website, you can store `url`.

`downloadUrl` is a convenience property that will ensure, when opened by a browser, the file will be downloaded to your user's computer.

`downloadUrl` is `${url}?download=1`

Let me know if this is clear or not 👍

**Comment by Vimblin** [comment]
> @Swoopify To display the avatar on a website, you can store `url`.
> 
> `downloadUrl` is a convenience property that will ensure, when opened by a browser, the file will be downloaded to your user's computer.
> 
> `downloadUrl` is `${url}?download=1`
> 
> Let me know if this is clear or not 👍 
> 
> 

Thank you, now it is clear for me ^^
