### ISSUE TITLE
How to process blob after upload before saving when using client uploads in vercel blob for image/video compression

### ISSUE THREAD

**Issue by Jamzy01** [vercel/storage#698]
I want to compress images and videos down after the user has uploaded the file using a client upload. I don't want to include sharp in the client build since it'd be terrible for performance, plus I can't use ffmpeg on the client for compressing videos. Additionally, I can't really trust the user to compress the images themselves, I'd much rather do it on the server. I understand that vercel blob is clearly still quite limited, but this feature is a necessity unless I want my blob to fill up incredibly fast.

**Comment by vvo** [comment]
Hey @Jamzy01 to achieve video or image compression, if it's not done on the client side, then you need to do it on the server side. Vercel Blob is currently an object-storage system, and as such, it doesn't include automatic image or video optimization.

What you could is:
- upload files to an API that would optimize them, like https://www.freeconvert.com/api/video-conversion-api
- get the optimized files URLs
- import optimized files into Vercel Blob
 
Please note that the exact way to achieve this will depend on your chosen optimization API and your own website.

Good luck!
