### ISSUE TITLE
High severity issue found in @vercel/postgres

### ISSUE THREAD

**Issue by Kaushal-Saraf** [vercel/storage#701]
Severity: high
ws affected by a DoS when handling a request with many HTTP headers - https://github.com/advisories/GHSA-3h5v-q93c-6h6q        
No fix available
node_modules/ws
  @vercel/postgres  *
  Depends on vulnerable versions of ws
  node_modules/@vercel/postgres

2 high severity vulnerabilities

**Comment by luismeyer** [comment]
thank you. Renovate bot already created a PR for this: https://github.com/vercel/storage/pull/697
