### ISSUE TITLE
The method "copy" is not working when the url contains "ñ" character 

### ISSUE THREAD

**Issue by sudosuberenu** [vercel/storage#720]
The next line takes forever when the "fromImageUrl" contains "ñ" character. I guess it will happen also for another "strange" character.

const blob = await copy(fromImageUrl, destionationFolder, { access: 'public' });

**Comment by vvo** [comment]
Hey @sudosuberenu better late than never: we're fixing this as we speak and the fix will be deployed in ~10 minutes. Thanks again for reporting this issue!
