### ISSUE TITLE
Restrict file type

### ISSUE THREAD

**Issue by musjj** [vercel/storage#722]
Is there a way to restrict the type of files users are allowed to upload? `File.type` and `PutBlobResult.contentType` is based on file extension, so it's not really reliable for validation.

Is there a more reliable method?

**Comment by vvo** [comment]
Hey, @musjj, we infer the content type of files from their extension, indeed. If you need a more precise way to restrict the type of files, you could create this on your side, like a route that would receive the first 5K bytes of the files and run https://github.com/sindresorhus/file-type on them. Based on the answer you could then proceed with the upload.

Or you could blindly accept the file, then on the onUploadCompleted route download the first bytes of the file (range request) and pass them again in file-type module.

There are a lot of solutions here, but the tl;dr; is that you will want to use magic numbers (= file-type module) to restrict file types of files with bad or no extensions.
