### ISSUE TITLE
Safari: Refused to apply a stylesheet for PDF views

### ISSUE THREAD

**Issue by TechEclipse** [vercel/storage#728]
**Description**

If you open a pdf in Safari that was uploaded to the vercel storage as blob and set to public an error is logged to the console:
`Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' appears in neither the style-src directive nor the default-src directive of the Content Security Policy.` that results in rendering the pdf in a height of 154px. There is no problem in other bigger browsers (Chrome or Firefox) but unfortunately our users also using Safari and wants to open the PDF in a new Tab within the browser. Is it possible to adjust the CSP Headers accordingly so PDF's are rendered in full size in Safari?

**To reproduce**

- Upload a pdf through @vercel/blob to your storage with the option `access: 'public'`
- Get the URL of the PDF and open it in Safari
- Open the developer console and see the mentioned error

**Used versions**

- Safari 17.5
- MacOS 14.5
- @vercel/blob 0.23.4

**Comment by vvo** [comment]
Hey @TechEclipse we're looking into this right now, this is a Safari bug and we're digging on how to solve it properly.
https://bugs.webkit.org/show_bug.cgi?id=166630

**Comment by vvo** [comment]
Hey @TechEclipse, we deployed a change and now pdf preview will work correctly in Safari: https://ikycltsnmoaacgtb.public.blob.vercel-storage.com/sample-2z1edkvm5KDSpeEUJ2vJrWCv2RXAL8.pdf
