### ISSUE TITLE
Redis Client Connection Errors

### ISSUE THREAD

**Issue by jb-dev1** [vercel/storage#731]
I've tried a few Redis clients and they are reporting connection errors, so I believe it's how I'm configuring them.

From the Vercel Storage tab / quickstart info (CLI/cURL/fetch/etc) auth info, what do I utilize in a database client like Redis Insight to get a UI / real time monitor app working?

**Comment by vvo** [comment]
Hey there @jb-dev1, I just gave a try to Redis Insight and this is how I configured it (it worked) 👇 

![CleanShot 2024-07-31 at 15 41 36@2x](https://github.com/user-attachments/assets/080daed4-0ba1-4681-8bbb-6b3d8ce97a33)

![CleanShot 2024-07-31 at 15 40 59@2x](https://github.com/user-attachments/assets/73ea9dc4-24ae-4f5f-b424-d0aa60ecdf70)

Hope this helps 👍 

![CleanShot 2024-07-31 at 15 58 09@2x](https://github.com/user-attachments/assets/13399e21-a4ec-455b-a119-49cc5bc70cba)

**Comment by jb-dev1** [comment]
You're a champion, thank you. I had forgotten about the TLS requirement, and the Vercel KV response messages were not meaningful (to me anyway).
