### ISSUE TITLE
Local database with vercel/postgres

### ISSUE THREAD

**Issue by lukasz-rek** [vercel/storage#732]
Hi, 

I'm new to Vercel and I can't find what is the recommended way of running the application locally and connecting to a local postgres database.

Currently, I'm trying to follow the steps outlined in #123, however it does seem that the issue wasn't fully closed with people still having problems. Even when running the neon client, I simply still get 'ECONNREFUSED' error, while I can connect to the database locally so it is running.

I'm using the docker image from [here](https://gal.hagever.com/posts/running-vercel-postgres-locally), but it seems to require using `db` instead of `sql`, with an example like this (with rest of the app omitted). I'd prefer to avoid switching to db, as sql seems to be the preferred option.
```
import { sql } from "@vercel/postgres"

const data = await sql'SELECT * FROM TABLE';
```
with
 ```
POSTGRES_URL= postgres://username:password@localhost:5433/postgres?sslmode=require # port 5432 also doesn't work
```
Is there an error with the way I'm doing it now? The documentation seems pretty lacklustre for such a basic thing, yet it'd be a shame if it's not supported or requires paying for an another tier just to test locally :/

**Comment by vvo** [comment]
Hey there, here's how to have a local Postgres database and connect to it with `@vercel/postgres`: https://github.com/vercel/storage/issues/123#issuecomment-2326100123
