### ISSUE TITLE
Blob images won't display in web app, but can be viewed by direct link

### ISSUE THREAD

**Issue by enlguy** [vercel/storage#780]
This is similar to https://github.com/vercel/storage/issues/407, however I keep getting type errors with the suggested syntax from that thread.

Images from blob load on visiting direct URL, but will not load in the app.  

I'm not sure how much code to paste here....  Effectively there is a wrapper with types created for this.  There are two main wrappers, one for user, one for other profiles (social site).  The types are setup the same, and the code is the same for displaying the photo gallery component, just changing out a {user} object for a {dateProfile} object.  Each has its own page.tsx, though.  Profile photos for current user display fine when logged in and visiting your own profile page.  The photos NEVER load for other users, though.  All photos uploaded to same blob in Vercel...

<PhotoGalleryWrapper profile={dateProfile} />      This is the component that should include the display of the photo gallery for another user.

const SLIDES = [
    <div
      key="slide1"
      className="m-3 mx-10 flex h-[335px] w-[335px] justify-center self-center smooth42transition sm:w-[400px] md:h-[400px]"
    >
      {user?.photos?.[0] ? (
        <Image
          src={`${profile?.photos?.[0]}`}
          alt="photo1"
          width={0}
          height={0}
          sizes="100vw" 
........

Slides is declared as an array, as the photos are stored as such, the type being declared as such:
  photos: z.array(z.string())

I have looked through so much code, but cannot find a reason the photos load okay for the current user, but no one else.  I have read there are often problems with Blobs in Vercel, but my own photos load okay, as stated.  Other photos are in the same Blob, but not loading.

**Comment by luismeyer** [comment]
Hey @enlguy,

this is pretty likely not a Blob Issue but something in your App. From quickly looking at your Repo (I assume it's this one: https://github.com/enlguy/date-main) I see that you are taking the user data in the `src/app/[locale]/(dashboard)/search/[id]/page.tsx` file either from the Suggestions or from your Search endpoint. The Search Endpoint is querying the Photos from your DB but the Suggestions endpoint is not. 

Also I see that in you script to populate the DB you are using this Blob store URL `kdbxq6eseiqtwhzx.public.blob.vercel-storage.com/...` but in your next.config.js you have just white listed `ol5febquycnr2hzu.public.blob.vercel-storage.com`. Make sure to whitelist all domains in your config.

Hope this helps 🙏

**Comment by enlguy** [comment]
Thank you.  I see you closed this as soon as you posted your own response, which I don't understand....

As it were, though, this has helped a lot.  I'm working with some existing code, and didn't realize the photos hadn't been added to all the routes.  Photos are displaying now.
