### ISSUE TITLE
Cannot delete Vercel Blob Storage in Vercel Account

### ISSUE THREAD

**Issue by jb-dev1** [vercel/storage#783]
And the most ridiculous thing is that your Support funciton is broken too. I cannot submit a support request because your terrible UI won't let me select the severity level.  What has happened to Vercel?  So many project are broken.  Next.js 14 was a disaster. The Vercel website is a disaster. `ai-chatbot` is a disaster. The Vercel AI SDK RSCs toolkit was an unmitigated disaster. I tried setting up the `gemini-chatbot` and had numerous errors. Now I can't delete the Vercel Blob storage and just get an error, and I can't open a support ticket.

WHAT KIND OF A COMPANY HAS THIS MANY ERRORS ACROSS ALL SYSTEMS, PLATFORMS, AND WEBSITES?  I'm trying to build a chatbot for a Fortune 100 company and I've clearly made a serious mistake in choosing Vercel and Next.js.

![image](https://github.com/user-attachments/assets/6cd30a51-6637-467f-9ec2-47523fe41e90)

![image](https://github.com/user-attachments/assets/4f2fc416-cfa1-4832-a6a2-cfb788aae1a7)

**Comment by luismeyer** [comment]
Hey @jb-dev1,
I apologize for any inconvenience this has caused you. Thank you for bringing this issue to our attention. We've identified and resolved a bug in our API that was causing errors when attempting to delete stores associated with previously deleted projects.

Would you mind trying the deletion again? I'd appreciate your feedback on whether this resolves the issue for you.

Please don't hesitate to update this ticket if you encounter any further problems.
Best regards,
Luis

**Comment by luismeyer** [comment]
closing this now. Feel free to reopen if the Problem persists
