### ISSUE TITLE
Client upload size confusion

### ISSUE THREAD

**Issue by hugohabicht01** [vercel/storage#789]
Hey,
in the file at `packages/blob/README.md` it says that the maximum upload size for a client upload is 500MB, while the docs at https://vercel.com/docs/storage/vercel-blob#server-and-client-uploads state 5TB. It would be great if you could clarify which one is correct
Thanks

**Comment by vvo** [comment]
Thx @hugohabicht01, I fixed the README here: https://github.com/vercel/storage/pull/790.
It's 5 TB
