### ISSUE TITLE
Failed to upload picture: BlobStoreNotFoundError: Vercel Blob: This store does not exist.

### ISSUE THREAD

**Issue by alexanderalvarado91** [vercel/storage#795]
I get BlobStoreNotFoundError when I try to upload a picture. I have a store available. And my project is connected to Vercel's project.

`
  
    form.parse(req, async (err, fields, files) => {
      if (err) {
        console.error('Error parsing form data:', err);
        return res.status(400).send({ error: 'Failed to parse form data' });
      }
  
      console.log('Parsed fields:', fields);
      console.log('Parsed files:', files);
  
      const fileField = files.file;
      const file = Array.isArray(fileField) ? fileField[0] : fileField;
  
      if (!file) {
        console.error('File field is missing or incorrect');
        return res.status(400).send({ error: 'No file uploaded' });
      }
  
      const compressedImagePath = path.join(__dirname, 'temp', `${Date.now()}_${file.newFilename}`);
  
      try {
        console.log('File received for compression:', file.filepath);
  
        await sharp(file.filepath)
          .resize(800)
          .jpeg({ quality: 80 })
          .toFile(compressedImagePath);
  
        console.log('Compressed image created at:', compressedImagePath);
  
        const fileData = fs.readFileSync(compressedImagePath);
  
        const blob = await put(file.newFilename, fileData, {
          access: 'public',
        });
  
        console.log('File uploaded to Vercel Blob. URL:', blob.url);
  
        // Clean up temporary files
        fs.unlink(file.filepath, (err) => {
          if (err) console.error('Error deleting original file:', err);
        });
        fs.unlink(compressedImagePath, (err) => {
          if (err) console.error('Error deleting compressed file:', err);
        });
  
        return res.status(200).send({
          message: 'Picture uploaded successfully',
          picture: blob.url,
        });
      } catch (error) {
        console.error('Failed to upload picture:', error);
  
        fs.unlink(file.filepath, (err) => {
          if (err) console.error('Error deleting original file:', err);
        });
        fs.unlink(compressedImagePath, (err) => {
          if (err) console.error('Error deleting compressed file:', err);
        });
  
        return res.status(500).send({
          error: 'Failed to upload picture',
        });
      }
    });
  };`

**Comment by luismeyer** [comment]
Hey @alexanderalvarado91,
Is this happening only locally or only on your Deployment? Can you make sure the `BLOB_READ_WRITE_TOKEN` Environment Variable is set to the correct Value?

**Comment by alexanderalvarado91** [comment]
Yes, the solution was to reset the token.
