### ISSUE TITLE
client side fetching blob url causes CORS error

### ISSUE THREAD

**Issue by hcapp01** [vercel/storage#812]
CODE:    
const response = await fetch(REMOTE_UNITS_URL, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type'
      }
    });
 
ERROR:
    Access to fetch at 'https://xxxx.public.blob.vercel-storage.com/json/xxx.json' from origin 'http://localhost:3002' has been blocked by CORS policy: Request header field access-control-allow-methods is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by luismeyer** [comment]
hey @hcapp01, 
currently only successful requests to existing blobs will respond with `Access-Control-Allow-Origin': *`. Is there any particular reason you are trying to fetch non existing blob urls?

**Comment by hcapp01** [comment]
@luismeyer It does exist. I masked file name with "xxx" in previous log. 
If you really need the exact file for repro, here is the unmasked version:

Access to fetch at 'https://5x49eqvt11cu7lab.public.blob.vercel-storage.com/test-NVtvKAmCrwPQSPTbrhxJbqEra7M76s' from origin 'http://localhost:3001' has been blocked by CORS policy: Request header field access-control-allow-headers is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by luismeyer** [comment]
ah sorry I missed that this is a Access-Control-Allow-Headers error.
This is solvable by not passing any headers to fetch. Any reason you are passing these in the first place? CORS headers are sent by the server not by the client.
